# Generated by Django 4.1.2 on 2023-07-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_customuser_abonelik_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_gider_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ana Gider Kodu')),
                ('gider_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gider Kodu')),
                ('birim', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birim')),
                ('detay', models.CharField(blank=True, choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=100, null=True, verbose_name='Detay')),
                ('borc_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Borç Tutarı (TL)')),
                ('alacak_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Alacak Tutarı (TL)')),
                ('bakiye_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Bakiye Tutarı (TL)')),
                ('doviz_cinsi', models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('$', '$'), ('£', '£')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi')),
                ('kdv_orani', models.CharField(blank=True, max_length=100, null=True, verbose_name='KDV Oranı')),
                ('ozel_kod', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Özel Kod')),
                ('birim_fiyati', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Fiyatı')),
                ('birim_fiyati_doviz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Fiyatı Döviz')),
                ('muh_kodu1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muh. Kodu 1')),
                ('muh_kodu2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muh. Kodu 2')),
                ('kdv_muh_kodu2', models.CharField(blank=True, max_length=100, null=True, verbose_name='KDV Muh. Kodu 2')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
        migrations.CreateModel(
            name='gelir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_gelir_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ana gelir Kodu')),
                ('gelir_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='gelir Kodu')),
                ('birim', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birim')),
                ('detay', models.CharField(blank=True, choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=100, null=True, verbose_name='Detay')),
                ('borc_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Borç Tutarı (TL)')),
                ('alacak_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Alacak Tutarı (TL)')),
                ('bakiye_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Bakiye Tutarı (TL)')),
                ('doviz_cinsi', models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('$', '$'), ('£', '£')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi')),
                ('kdv_orani', models.CharField(blank=True, max_length=100, null=True, verbose_name='KDV Oranı')),
                ('ozel_kod', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Özel Kod')),
                ('birim_fiyati', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Fiyatı')),
                ('birim_fiyati_doviz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Fiyatı Döviz')),
                ('muh_kodu1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muh. Kodu 1')),
                ('muh_kodu2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muh. Kodu 2')),
                ('kdv_muh_kodu2', models.CharField(blank=True, max_length=100, null=True, verbose_name='KDV Muh. Kodu 2')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
