# Generated by Django 4.1.2 on 2023-07-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelir_gider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gelir',
            name='kdv_muh_kodu2',
        ),
    ]
