from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(banka)
admin.site.register(banka_yetkilisi)
admin.site.register(tevkifat_tur_kodu)
admin.site.register(HesapPlanlari)
admin.site.register(banka_kart_bilgileri)
admin.site.register(Kasa)
admin.site.register(Giderler)
admin.site.register(Gelirler)
admin.site.register(kasa_fisleri)
admin.site.register(cari_kartlar)
admin.site.register(ulke_ulke_kodlari)
admin.site.register(cari_kartislemleri_adresleri_kimlik)
admin.site.register(cari_kartislemleri_diger_bilgiler)
admin.site.register(cari_kartislemleri_notlar)
admin.site.register(cari_kartislemleri_firma_gorevilisi)
admin.site.register(cari_kartislemleri_sube_bilgiler)
admin.site.register(banka_kodlari)
admin.site.register(banka_notlari)
admin.site.register(banka_kredikartibilgileri)
admin.site.register(KasaFisIslemleri)
admin.site.register(kdv_istisna_kodu)
admin.site.register(stok_kartlar)
admin.site.register(stok_birim_alis_satis_birimi)
admin.site.register(bankaFisIslemleri)
admin.site.register(cari_fisleri)
admin.site.register(stok_alis_satis)
admin.site.register(stok_kodlari)
admin.site.register(stok_detaylari)
admin.site.register(stok_recetesi)
admin.site.register(stok_muhasabe_kodlari)
admin.site.register(stok_muhasebe_kodlari_evraklar)
admin.site.register(stok_iliskili_gider_gelir)
admin.site.register(stok_diger_kismi_otv)
admin.site.register(stok_diger_kismi_agirliklar)
admin.site.register(stok_diger_birim_durumu)
#admin.site.register(siparis_olustur)
admin.site.register(dilekceler)
#admin.site.register()
#admin.site.register()



