# Generated by Django 4.1.2 on 2023-06-26 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='entkodu',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2')], default='', max_length=10, null=True, verbose_name='Ent Kodu'),
        ),
        migrations.AlterField(
            model_name='banka',
            name='hesap_turu',
            field=models.CharField(blank=True, choices=[('', ''), ('Ticari', 'Ticari'), ('Kredi', 'Kredi'), ('Kredi Kartı', 'Kredi Kartı')], default='', max_length=100, null=True, verbose_name='Hesap Turu'),
        ),
        migrations.CreateModel(
            name='banka_yetkilisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banka Yetkilisi Adı Soyadı ')),
                ('gorevi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Görevi')),
                ('istelefonu', models.CharField(blank=True, max_length=20, null=True, verbose_name='İş Telefonu')),
                ('dahili_numara', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dahili Numara')),
                ('gsm', models.CharField(blank=True, max_length=100, null=True, verbose_name='GSM')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('banka_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.banka')),
            ],
        ),
    ]
