# Generated by Django 4.1.2 on 2023-07-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0003_tevkifat_tur_kodu_hesapplanlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesapplanlari',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='banka_yetkilisi',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.CreateModel(
            name='banka_kart_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahsilat_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tahsilat Kodu')),
                ('tahsilat_sekli', models.CharField(blank=True, choices=[('', ''), ('Tek Çekim', 'Tek Çekim'), ('Tek Çekim Taksitli', 'Tek Çekim Taksitli'), ('Taksitli Çekim', 'Taksitli Çekim')], default='', max_length=100, null=True, verbose_name='Tahsilat Şekilleri')),
                ('taksit_adedi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taksit Adedi')),
                ('taksit_araliklari_gun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taksit Aralıkları (Gün)')),
                ('banka_hesap_gecis_sekli', models.CharField(blank=True, choices=[('', ''), ('Hemen', 'Hemen'), ('Gecikmeli', 'Gecikmeli'), ('Taksitli', 'Taksitli')], default='', max_length=100, null=True, verbose_name='Banka Hesap Geçiş Şekli')),
                ('banka_hesap_gecis_gun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banka Hesap Geçiş (Gün)')),
                ('cari_hesap_kayit_sekli', models.CharField(blank=True, choices=[('', ''), ('Hemen', 'Hemen'), ('Gecikmeli', 'Gecikmeli'), ('Taksitli', 'Taksitli')], default='', max_length=100, null=True, verbose_name='Cari Hesap Kayıt Şekli')),
                ('komisyon_orani', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komisyon Oranı (%)')),
                ('komisyon_tutari', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komisyon Tutarı')),
                ('komisyon_kesinti_sekli', models.CharField(blank=True, choices=[('', ''), ('İlk Taksitle', 'İlk Taksitle'), ('Taksitlendirilmiş', 'Taksitlendirilmiş')], default='', max_length=100, null=True, verbose_name='Komisyon Kesinti Şekli')),
                ('komisyon_gider_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Komisyon Gider Kodu Tutarı')),
                ('promosyon_orani', models.CharField(blank=True, max_length=100, null=True, verbose_name='promosyon Oranı (%)')),
                ('promosyon_tutari', models.CharField(blank=True, max_length=100, null=True, verbose_name='promosyon Tutarı')),
                ('promosyon_kesinti_sekli', models.CharField(blank=True, choices=[('', ''), ('İlk Taksitle', 'İlk Taksitle'), ('Taksitlendirilmiş', 'Taksitlendirilmiş')], default='', max_length=100, null=True, verbose_name='promosyon Kesinti Şekli')),
                ('promosyon_gider_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Promosyon Gider Kodu Tutarı')),
                ('hizmet_orani', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hizmet Oranı (%)')),
                ('hizmet_tutari', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hizmet Tutarı')),
                ('hizmet_kesinti_sekli', models.CharField(blank=True, choices=[('', ''), ('İlk Taksitle', 'İlk Taksitle'), ('Taksitlendirilmiş', 'Taksitlendirilmiş')], default='', max_length=100, null=True, verbose_name='Hizmet Kesinti Şekli')),
                ('hizmet_gider_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hizmet Gider Kodu Tutarı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('hafta_sonuna_denk_gelmesin', models.CharField(blank=True, choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=100, null=True, verbose_name='Hafta Sonlarına Denk Gelmesin')),
                ('banka_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.banka')),
            ],
        ),
    ]
