# Generated by Django 4.1.2 on 2023-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0004_hesapplanlari_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='toplam_bakiye',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bakiye'),
        ),
        migrations.AddField(
            model_name='banka',
            name='toplam_cekilen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Toplam Çekilen'),
        ),
        migrations.AddField(
            model_name='banka',
            name='toplam_yatirilan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Toplam Yatırılan'),
        ),
        migrations.AlterField(
            model_name='banka',
            name='doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('turklirasi', 'TL'), ('euro', '£'), ('dolar', '$')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi'),
        ),
    ]
