# Generated by Django 4.1.2 on 2023-07-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0006_banka_muh_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
