# Generated by Django 4.1.2 on 2023-07-05 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_ortak_is_bilgileri_arac_plaka_no1_and_more'),
        ('bilgideposu', '0007_banka_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kasa Kodu')),
                ('entkodu', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2')], default='', max_length=10, null=True, verbose_name='Ent Kodu')),
                ('kasa_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='kasa Adı')),
                ('ozel_kod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Kod')),
                ('doviz_cinsi', models.CharField(blank=True, choices=[('', ''), ('turklirasi', 'TL'), ('euro', '£'), ('dolar', '$')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi')),
                ('toplam_tahsilat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Toplam Tahsilat')),
                ('toplam_odeme', models.CharField(blank=True, max_length=100, null=True, verbose_name='Toplam Ödeme')),
                ('toplam_bakiye', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bakiye')),
                ('muh_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Muh Kodu')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
