# Generated by Django 4.1.2 on 2023-09-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0009_cari_kartlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasa',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi'),
        ),
    ]
