# Generated by Django 4.1.2 on 2023-09-29 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0011_alter_cari_kartlar_cari_adi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kasa_fisleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_islemi', models.CharField(choices=[('', ''), ('Tahsilat Fişi', 'Tahsilat Fişi'), ('Ödeme Fişi', 'Ödeme Fişi'), ('Virman Fişi', 'Virman Fişi'), ('Döviz Fişi', 'Döviz Fişi'), ('Açılış Fişi', 'Açılış Fişi'), ('Kasa Tahsilat Makbuzu', 'Kasa Tahsilat Makbuzu'), ('Kasa Ödeme Makbuzu', 'Kasa Ödeme Makbuzu'), ('Maaş Ödeme (Kasa)', 'Maaş Ödeme (Kasa)'), ('Ödeme Fişi', 'Ödeme Fişi'), ('Tahsilat Fişi', 'Tahsilat Fişi'), ('Maaş Ödemesi (Kasa)', 'Maaş Ödemesi (Kasa)'), ('Bankaya Yatırılan', 'Bankaya Yatırılan'), ('Bankadan Çekilen', 'Bankadan Çekilen'), ('Çek/Senet Tahsili', 'Çek/Senet Tahsili'), ('Senet Ödemesi', 'Senet Ödemesi')], default='', max_length=200, verbose_name='Kasa Fiş İşlem Türü')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='İşlem Saati')),
                ('saat', models.TimeField(verbose_name='İşlem Saati')),
                ('evrak_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Evrak No')),
                ('entkodu', models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2')], default='', max_length=10, null=True, verbose_name='Ent Kodu')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('odeme_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Borç Tutarı (TL)')),
                ('tahsilat_tutari', models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Alacak Tutarı (TL)')),
                ('m', models.CharField(blank=True, max_length=10, null=True, verbose_name='M Bilgisi')),
                ('ozel_kod_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Kod 1')),
                ('ozel_kod_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Kod 2')),
                ('ent', models.CharField(blank=True, max_length=10, null=True, verbose_name='ent? Bilgisi')),
                ('uygunkur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uygun Kur')),
                ('departman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departman')),
                ('islemi_yapan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tahsilatı / Ödemeyi Yapan')),
                ('islemi_kaydeden_kullanici', models.CharField(blank=True, max_length=100, null=True, verbose_name='İşlemi Kaydeden Kullanıcı')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('banka_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.banka', verbose_name='Banka Bilgisi')),
                ('cari_unvan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.cari_kartlar', verbose_name='Cari Unvan Bilgisi')),
                ('gelri_bilgis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.gelirler', verbose_name='Gelir Bilgisi')),
                ('gider_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.giderler', verbose_name='Gider Bilgisi')),
                ('kasa_bilgis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilgideposu.kasa', verbose_name='Kasa Bilgisi')),
                ('sube_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sube', verbose_name='Gelir Bilgisi')),
            ],
        ),
    ]
