# Generated by Django 4.1.2 on 2023-09-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0012_kasa_fisleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari_kartlar',
            name='bagli_oldugu_firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma'),
        ),
    ]
