# Generated by Django 4.1.2 on 2023-10-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0014_cari_kartlar_silinme_bilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari_kartlar',
            name='muhkodu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muh. Kodu'),
        ),
        migrations.AddField(
            model_name='cari_kartlar',
            name='tevkifatkodu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tevkifat Kodu'),
        ),
    ]
