# Generated by Django 4.1.2 on 2023-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0015_cari_kartlar_muhkodu_cari_kartlar_tevkifatkodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cari_kartlar',
            name='alacak_tutari',
            field=models.BigIntegerField(blank=True, default='0', null=True, verbose_name='Alacak Tutarı (TL)'),
        ),
        migrations.AlterField(
            model_name='cari_kartlar',
            name='bakiye_tutari',
            field=models.BigIntegerField(blank=True, default='0', null=True, verbose_name='Bakiye Tutarı (TL)'),
        ),
        migrations.AlterField(
            model_name='cari_kartlar',
            name='borc_tutari',
            field=models.BigIntegerField(blank=True, default='0', null=True, verbose_name='Borç Tutarı (TL)'),
        ),
    ]
