# Generated by Django 4.1.2 on 2023-10-01 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0016_alter_cari_kartlar_alacak_tutari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari_kartlar',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
