# Generated by Django 4.1.2 on 2023-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0017_cari_kartlar_kayit_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ulke_ulke_kodlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulke_kodu', models.CharField(max_length=10, verbose_name='Ülke Kodu')),
                ('ulke_adi', models.CharField(max_length=200, verbose_name='Ülke Adı')),
            ],
        ),
        migrations.AlterField(
            model_name='cari_kartlar',
            name='takip_doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, null=True, verbose_name='Takip Döviz Cinsi'),
        ),
    ]
