# Generated by Django 4.1.2 on 2023-10-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0018_ulke_ulke_kodlari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cari_kartislemleri_adresleri_kimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 1 Bilgisi')),
                ('ilce', models.CharField(blank=True, max_length=200, null=True, verbose_name='İlçe Bilgisi')),
                ('il', models.CharField(blank=True, max_length=200, null=True, verbose_name='il Bilgisi')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Bilgisi')),
                ('faks', models.CharField(blank=True, max_length=20, null=True, verbose_name='Faks Bilgisi')),
                ('telefon2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon2 Bilgisi')),
                ('Telefon3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 3 Bilgisi')),
                ('gsm1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gsm1 Bilgisi')),
                ('gsm2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gsm2 Bilgisi')),
                ('posta_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Posta Kodu')),
                ('tc_veya_vergi_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='TC Veya Vergi No')),
                ('eposta_adresi', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Eposta Aderesi')),
                ('web_adresi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Adresi')),
                ('adres2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 2 Bilgisi')),
                ('ilce2', models.CharField(blank=True, max_length=200, null=True, verbose_name='İlçe Bilgisi')),
                ('il2', models.CharField(blank=True, max_length=200, null=True, verbose_name='il Bilgisi')),
                ('telefon4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Bilgisi')),
                ('faks2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Faks Bilgisi')),
                ('gsm3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gsm1 Bilgisi')),
                ('telefon5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gsm2 Bilgisi')),
                ('ulke2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ülke Bilgisi')),
                ('posta_kodu2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Posta Kodu')),
                ('adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='ADI Bilgisi')),
                ('soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='SOYADI Bilgisi')),
                ('babaadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='BABA ADI Bilgisi')),
                ('anneadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='ANNE ADI Bilgisi')),
                ('dogum_yeri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doğum Bilgisi')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cinsiyet Bilgisi')),
                ('seri_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seri No Bilgisi')),
                ('ssk_bagkur_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='SSK / Bağkur Bilgisi')),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilgideposu.cari_kartlar', verbose_name='Cari Bilgisi')),
                ('ulke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.ulke_ulke_kodlari', verbose_name='Cari Bilgisi')),
                ('vergi_dairesi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vergi_dairesi')),
            ],
        ),
    ]
