# Generated by Django 4.1.2 on 2023-10-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0019_cari_kartislemleri_adresleri_kimlik'),
    ]

    operations = [
        migrations.CreateModel(
            name='cari_kartislemleri_diger_bilgiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risklimiti', models.FloatField(blank=True, null=True, verbose_name='Risk Limiti')),
                ('digerdovizcinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='Döviz Cinsi')),
                ('faizvadefarki', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faiz Vade Farkı')),
                ('odemesuresigun', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ödeme Süresi Gün')),
                ('iskontoorani', models.FloatField(blank=True, null=True, verbose_name='İskonto Oranı')),
                ('karorani', models.FloatField(blank=True, null=True, verbose_name='Kar Oranı')),
                ('taksitsayisi', models.BigIntegerField(blank=True, null=True, verbose_name='Taksit Sayısı')),
                ('taksitodemegunuherayin', models.BigIntegerField(blank=True, null=True, verbose_name='Taksit Her Ayın Şu Günü')),
                ('satisfiyati', models.CharField(blank=True, max_length=100, null=True, verbose_name='Satış Fiyatı')),
                ('alisfiyati', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alış Fiyatı')),
                ('stokgrupkodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Grup Kodu')),
                ('iskontoorani2', models.FloatField(blank=True, null=True, verbose_name='İskonto Oranı')),
                ('indim1', models.CharField(blank=True, max_length=100, null=True, verbose_name='İndirim 1')),
                ('indim2', models.CharField(blank=True, max_length=100, null=True, verbose_name='İndirim 2')),
                ('indim3', models.CharField(blank=True, max_length=100, null=True, verbose_name='İndirim 3')),
                ('indim4', models.CharField(blank=True, max_length=100, null=True, verbose_name='İndirim 4')),
                ('indim5', models.CharField(blank=True, max_length=100, null=True, verbose_name='İndirim 5')),
                ('indim6', models.CharField(blank=True, max_length=100, null=True, verbose_name='İndirim 6')),
                ('uygunkursecenek', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uygun Kur ')),
                ('otvicin_kullan', models.BooleanField(default=False, verbose_name='ÖTV İçin Kullan')),
                ('bankaadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banka Adı')),
                ('subesi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Adı')),
                ('bankadovizcinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='Döviz Cinsi')),
                ('hesapno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hesap No')),
                ('iban', models.CharField(blank=True, max_length=200, null=True, verbose_name='IBAN')),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilgideposu.cari_kartlar', verbose_name='Cari Bilgisi')),
            ],
        ),
    ]
