# Generated by Django 4.1.2 on 2023-10-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0020_cari_kartislemleri_diger_bilgiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='cari_kartislemleri_sube_bilgiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subebilgilerisubekodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Kodu')),
                ('subebilgilerisubeadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Adı')),
                ('subebilgileridovizcinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='Döviz Cinsi')),
                ('subebilgileriborctutari', models.FloatField(blank=True, null=True, verbose_name='Borç Tutarı')),
                ('subebilgilerialacaktutari', models.FloatField(blank=True, null=True, verbose_name='Alacak Tutarı')),
                ('subebilgileribakiyetutari', models.FloatField(blank=True, null=True, verbose_name='Bakiye Tutarı')),
                ('subebilgileriba', models.CharField(blank=True, max_length=10, null=True, verbose_name='Borçlu Alacaklı')),
                ('subebilgilerivadetarihi', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('subebilgileriadres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Adresi')),
                ('subebilgilerisemt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Şehir')),
                ('subebilgileritelefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('subebilgileriyetkili', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Yetkilisi')),
                ('subebilgileriodemesuresi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Ödeme Süresi')),
                ('subebilgilerivadehesapyonetimi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Yonetim HEsabı')),
                ('subebilgilerimuhkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Muhtasar Kodu')),
                ('subebilgileripostakodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube POsta Kodu')),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilgideposu.cari_kartlar', verbose_name='Cari Bilgisi')),
            ],
        ),
    ]
