# Generated by Django 4.1.2 on 2023-10-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0021_cari_kartislemleri_sube_bilgiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='cari_kartislemleri_notlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notlartarihi', models.DateField(blank=True, null=True, verbose_name='Notlar Tarihi')),
                ('notlarsatici', models.CharField(blank=True, max_length=200, null=True, verbose_name='Satıcı')),
                ('notlarnot', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilgideposu.cari_kartlar', verbose_name='Cari Bilgisi')),
            ],
        ),
    ]
