# Generated by Django 4.1.2 on 2023-10-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0022_cari_kartislemleri_notlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='cari_kartislemleri_firma_gorevilisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmagoreviadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Firme Görevili ADı Soyadı')),
                ('firmagorevligorevi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Görevli Görevi')),
                ('firmagorevliistelefonu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Görevli Telefon Numarası')),
                ('firmagorevlidahilinumara', models.CharField(blank=True, max_length=20, null=True, verbose_name='Firma FGörevil iTelefon Dahili Numara')),
                ('firmagorevligsm', models.CharField(blank=True, max_length=20, null=True, verbose_name='Firma Görevili Gsm')),
                ('firmaaciklama', models.TextField(blank=True, null=True, verbose_name='Firma Açıklama')),
                ('cari_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bilgideposu.cari_kartlar', verbose_name='Cari Bilgisi')),
            ],
        ),
    ]
