# Generated by Django 4.1.2 on 2023-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0023_cari_kartislemleri_firma_gorevilisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cari_kartislemleri_sube_bilgiler',
            name='subebilgilerisehir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Şube Şehir'),
        ),
        migrations.AlterField(
            model_name='cari_kartislemleri_sube_bilgiler',
            name='subebilgilerisemt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ŞubeSemt Bilgisi'),
        ),
    ]
