# Generated by Django 4.1.2 on 2023-10-03 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0025_remove_banka_muh_kodu_alter_banka_toplam_bakiye_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banka_notlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banka_nottarihi', models.DateField(blank=True, null=True, verbose_name='Not Tarihi')),
                ('banka_not', models.TextField(blank=True, null=True, verbose_name='Not ')),
                ('banka_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.banka')),
            ],
        ),
        migrations.CreateModel(
            name='banka_kodlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banka_muhasebe_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banka Muhasebe Hesap Kodu ')),
                ('kredi_kartı_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kredi Kartı Hesap Kodu')),
                ('verilen_cekler_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Verilen Çekler Hesap Kodu ')),
                ('tahsil_cekler_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tahsil Çekleri Hesap Kodu')),
                ('tahsil_senetleri_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tahsil Senetleri Hesap Kodu ')),
                ('teminat_cekler_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teminat Çekleri Hesap Kodu')),
                ('teminat_senetleri_hesap_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teminat Senetleri Hesap Kodu')),
                ('ilgilikisi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İlgili Kişi')),
                ('telefonbilgisi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Bilgisi')),
                ('adresbilgisi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres Bilgisi')),
                ('banka_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.banka')),
            ],
        ),
    ]
