# Generated by Django 4.1.2 on 2023-10-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0026_banka_notlari_banka_kodlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='banka_kredikartibilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahsilatkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tahsilat Kodu')),
                ('tahsilatsekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tahsilat Şekli')),
                ('taksitadedi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taksitli Çekim')),
                ('taksitaralikligun', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taksitli Çekim')),
                ('bankahesabinagecissekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banka Hesabına Geçiş Şekli')),
                ('hesabagecissuresigun', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hesaba Geçiş Süresi Gün')),
                ('carihesapkayitsekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cari Hesap Geçiş Şekli')),
                ('komisyonorani', models.CharField(blank=True, max_length=200, null=True, verbose_name='Komisyon Oranı')),
                ('komisyontutari', models.CharField(blank=True, max_length=200, null=True, verbose_name='Komisyon Tutarı')),
                ('komisyongiderkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Komisyon gider Kodu')),
                ('promosyonorani', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promosyon Oranı')),
                ('promosyontutari', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promosyon Tutarı')),
                ('promosyonkesintisekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promosyon Kesinti Şekli')),
                ('promosyongiderkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Promosyon Gider Kodu')),
                ('hizmetorani', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet Oranı')),
                ('hizmettutari', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet Tutarı')),
                ('hizmetgiderkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet Gider Kodu')),
                ('hizmetkesintisekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet Kesinti Şekli')),
                ('kredikartaciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('taksitgunleri', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taksit Günleri Hafta Sonuna Denk Gelmesin')),
                ('banka_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.banka')),
            ],
        ),
    ]
