# Generated by Django 4.1.2 on 2023-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0027_banka_kredikartibilgileri'),
    ]

    operations = [
        migrations.AddField(
            model_name='banka',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
