# Generated by Django 4.1.2 on 2023-10-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0028_banka_silinme_bilgisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='iban_numarasi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='İban Numarası'),
        ),
    ]
