# Generated by Django 4.1.2 on 2023-10-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0029_alter_banka_iban_numarasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasaFisIslemleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('', ''), ('Tahsilat Fişi', 'Tahsilat Fişi'), ('Ödeme Fişi', 'Ödeme Fişi'), ('Virman Fişi', 'Virman Fişi'), ('Döviz Fişi', 'Döviz Fişi'), ('Açılış Fişi', 'Açılış Fişi'), ('Tahsilat Makbuzu', 'Tahsilat Makbuzu'), ('Ödeme Makbuzu', 'Ödeme Makbuzu'), ('Maaş Ödemesi', 'Maaş Ödemesi')], default='', max_length=200, verbose_name='İşlem Türü')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='İşlem Tarihi')),
                ('saat', models.TimeField(blank=True, null=True, verbose_name='İşlem Saati')),
                ('evrak_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Evrak Tarihi')),
                ('ent_kodu', models.CharField(choices=[('', ''), ('1', '1'), ('2', '2')], default='', max_length=2, verbose_name='Ent Kodu')),
                ('ozelkod1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod')),
                ('ozelkod2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod 2')),
                ('birinci_departman', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departman')),
                ('birinci_kasa_muh_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kasa Muhtasar Kodu')),
                ('gelir_muh_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gelir Muhtasar Kodu')),
                ('islem_doviz_cinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='İşlem Döviz Cinsi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='İşlem Açıklama ')),
                ('islemi_yapan', models.CharField(blank=True, max_length=250, null=True, verbose_name='İşlemi Yapan')),
                ('tutar', models.FloatField(blank=True, null=True, verbose_name='İşlem Tutarı')),
                ('gider_muh_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gİder Muhtasar Kodu')),
                ('ikinci_departman', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departman')),
                ('ikinci_kasa_muh_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kasa Muhtasar Kodu')),
                ('islem_durumu', models.BooleanField(default=False, verbose_name='İşlem Tamamlandıysa tikli olacak')),
                ('satici', models.CharField(blank=True, max_length=200, null=True, verbose_name='SAtıcı')),
                ('kampkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kamp Kodu')),
                ('gunluk_kur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Günlük Kur')),
                ('uygun_kur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Uygun Kur')),
                ('birinci_kasa_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birinci_kasa_fis_islemleri_set', to='bilgideposu.kasa', verbose_name='Birinci Kasa Bilgisi')),
                ('birinciislem_sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birinciislem_kasa_fis_islemleri_set', to='users.sube', verbose_name='Şube')),
                ('gelir_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gelir_kasa_fis_islemleri_set', to='bilgideposu.gelirler', verbose_name='Gelir Bilgisi')),
                ('gider_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gider_kasa_fis_islemleri_set', to='bilgideposu.giderler', verbose_name='Gelir Bilgisi')),
                ('ikinci_gelir_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinci_gelir_kasa_fis_islemleri_set', to='bilgideposu.gelirler', verbose_name='Gelir Bilgisi')),
                ('ikinci_gider_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinci_gider_kasa_fis_islemleri_set', to='bilgideposu.giderler', verbose_name='Gelir Bilgisi')),
                ('ikinci_islem_sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinciislem_kasa_fis_islemleri_set', to='users.sube', verbose_name='Şube')),
                ('ikinci_kasa_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinci_kasa_fis_islemleri_set', to='bilgideposu.kasa', verbose_name='İkinci Kasa Bilgisi')),
            ],
        ),
    ]
