# Generated by Django 4.1.2 on 2023-10-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0030_kasafisislemleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='bagli_oldugu_firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma'),
        ),
        migrations.AlterField(
            model_name='kasafisislemleri',
            name='islem_turu',
            field=models.CharField(choices=[('', ''), ('Tahsilat Fişi', 'Tahsilat Fişi'), ('Ödeme Fişi', 'Ödeme Fişi'), ('Virman Fişi', 'Virman Fişi'), ('Döviz Fişi', 'Döviz Fişi'), ('Açılış Fişi', 'Açılış Fişi'), ('Kasa Tahsilat Makbuzu', 'Kasa Tahsilat Makbuzu'), ('Kasa Ödeme Makbuzu', 'Kasa Ödeme Makbuzu'), ('Maaş Ödeme (Kasa)', 'Maaş Ödeme (Kasa)'), ('Ödeme Fişi', 'Ödeme Fişi'), ('Tahsilat Fişi', 'Tahsilat Fişi'), ('Maaş Ödemesi (Kasa)', 'Maaş Ödemesi (Kasa)'), ('Bankaya Yatırılan', 'Bankaya Yatırılan'), ('Bankadan Çekilen', 'Bankadan Çekilen'), ('Çek/Senet Tahsili', 'Çek/Senet Tahsili'), ('Senet Ödemesi', 'Senet Ödemesi')], default='', max_length=200, verbose_name='İşlem Türü'),
        ),
    ]
