# Generated by Django 4.1.2 on 2023-10-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0031_kasafisislemleri_bagli_oldugu_firma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasa',
            name='toplam_bakiye',
            field=models.FloatField(blank=True, null=True, verbose_name='Bakiye'),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='toplam_odeme',
            field=models.FloatField(blank=True, null=True, verbose_name='Toplam Ödeme'),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='toplam_tahsilat',
            field=models.FloatField(blank=True, null=True, verbose_name='Toplam Tahsilat'),
        ),
    ]
