# Generated by Django 4.1.2 on 2023-10-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0032_alter_kasa_toplam_bakiye_alter_kasa_toplam_odeme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
