# Generated by Django 4.1.2 on 2023-10-04 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0033_kasafisislemleri_silinme_bilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='cari_unvan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.cari_kartlar', verbose_name='Cari Unvan Bilgisi'),
        ),
    ]
