# Generated by Django 4.1.2 on 2023-10-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0035_kasafisislemleri_banka_bilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='doviz_tutar',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Tutarı döviz'),
        ),
    ]
