# Generated by Django 4.1.2 on 2023-10-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0036_kasafisislemleri_doviz_tutar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='alacakbilgisi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='alacakbilgisi'),
        ),
    ]
