# Generated by Django 4.1.2 on 2023-10-05 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0037_kasafisislemleri_alacakbilgisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='kendisi_secme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bilgideposu.kasafisislemleri', verbose_name='makbuzlar için'),
        ),
    ]
