# Generated by Django 4.1.2 on 2023-10-05 14:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0039_kdv_istisna_kodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_kartlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ana_stok_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ana Stok Kodu')),
                ('detay', models.CharField(blank=True, choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=100, null=True, verbose_name='Detay')),
                ('listede_gorunsun', models.CharField(blank=True, choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=100, null=True, verbose_name='Listede Görünsün')),
                ('stok_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('stok_turu', models.CharField(blank=True, choices=[('', ''), ('Hammadde', 'Hammadde'), ('Yarı Mamul', 'Yarı Mamul'), ('Mamul', 'Mamul'), ('Ticari Mal', 'Ticari Mal'), ('Demirbaş', 'Demirbaş')], default='', max_length=100, null=True, verbose_name='Stok Türü')),
                ('stok_hesap_kilitli', models.CharField(blank=True, choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=100, null=True, verbose_name='Stok Hesap Kilitli')),
                ('silinme_bilgisi', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='stokkartiimage/', verbose_name='Stok kartı resmi')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
        migrations.CreateModel(
            name='stok_birim_alis_satis_birimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinci_birim', models.CharField(choices=[('', ''), ('Adet', 'Adet')], default='', max_length=100, verbose_name='Birinci  Birim')),
                ('ikinci_birim', models.CharField(choices=[('', ''), ('Adet', 'Adet')], default='', max_length=100, verbose_name='İkinci  Birim')),
                ('ucuncu_birim', models.CharField(choices=[('', ''), ('Adet', 'Adet')], default='', max_length=100, verbose_name='Ücüncü  Birim')),
                ('ikinci_birim_deger', models.CharField(blank=True, max_length=100, null=True, verbose_name='İkinci  Birim')),
                ('ucuncu_birim_deger', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ücüncü  Birim')),
                ('ikinci_birim_islem', models.CharField(blank=True, max_length=100, null=True, verbose_name='İkinci  İşlem')),
                ('ucuncu_birim_islem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ücüncü  İşlem')),
                ('max_stok_miktari', models.FloatField(blank=True, null=True, verbose_name='Max Stok Miktarı')),
                ('min_stok_miktari', models.FloatField(blank=True, null=True, verbose_name='Min Stok Miktarı')),
                ('serbest_stok_birimi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Serbest Stok Brimi')),
                ('indirim1', models.FloatField(blank=True, null=True, verbose_name='İndirim 1')),
                ('indirim2', models.FloatField(blank=True, null=True, verbose_name='İndirim 2')),
                ('indirim3', models.FloatField(blank=True, null=True, verbose_name='İndirim 3')),
                ('satis_birimi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Satış Birimi Seç')),
                ('aliss_birimi', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alış Birimi Seç')),
                ('kdv_orani', models.FloatField(blank=True, null=True, verbose_name='KDV ORanı')),
                ('tevkifat_orani', models.CharField(max_length=20, verbose_name='Tev')),
                ('lot_kullanimi', models.CharField(choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=20, verbose_name='Lot Kullan')),
                ('kdv_istisna_kodu_sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv_istisna_kodu', verbose_name='KDV İstisna Kodu')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_karti_bilgisi_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
