# Generated by Django 4.1.2 on 2023-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0041_kdv_istisna_kodu_kod_bilgi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok_kartlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stokkartiimage/', verbose_name='Stok kartı resmi'),
        ),
    ]
