# Generated by Django 4.1.2 on 2023-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0043_stok_kartlar_stok_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok_birim_alis_satis_birimi',
            name='serinokullan',
            field=models.CharField(choices=[('', ''), ('Evet', 'Evet'), ('Hayır', 'Hayır')], default='', max_length=20, verbose_name='Seri No Kullan'),
        ),
        migrations.AddField(
            model_name='stok_birim_alis_satis_birimi',
            name='temin_gun',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Temin Gün'),
        ),
    ]
