# Generated by Django 4.1.2 on 2023-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0045_alter_banka_doviz_cinsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='tutar_tl',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Tutarı (TL)'),
        ),
    ]
