# Generated by Django 4.1.2 on 2023-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0046_kasafisislemleri_tutar_tl'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='gider_durumu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gider Durumu'),
        ),
    ]
