# Generated by Django 4.1.2 on 2023-10-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0047_kasafisislemleri_gider_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='gideryuzdesi',
            field=models.FloatField(blank=True, null=True, verbose_name='Gider yüzdesi'),
        ),
    ]
