# Generated by Django 4.1.2 on 2023-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0048_kasafisislemleri_gideryuzdesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasafisislemleri',
            name='banka_kasa_muh_kodu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banka Muhtasar Kodu'),
        ),
    ]
