# Generated by Django 4.1.2 on 2023-10-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0051_bankafisislemleri_slem_sonucu_bakiye_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankafisislemleri',
            old_name='slem_sonucu_bakiye',
            new_name='islem_sonucu_bakiye_birinci_banka',
        ),
        migrations.RenameField(
            model_name='kasafisislemleri',
            old_name='islem_sonucu_bakiye',
            new_name='islem_sonucu_bakiye_banka',
        ),
        migrations.AddField(
            model_name='bankafisislemleri',
            name='islem_sonucu_bakiye_cari',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Sonucu Bakiye'),
        ),
        migrations.AddField(
            model_name='bankafisislemleri',
            name='islem_sonucu_bakiye_ikinci_banka',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Sonucu Bakiye'),
        ),
        migrations.AddField(
            model_name='bankafisislemleri',
            name='islem_sonucu_bakiye_kasa',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Sonucu Bakiye'),
        ),
        migrations.AddField(
            model_name='kasafisislemleri',
            name='islem_sonucu_bakiye_birinci_kasa',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Sonucu Bakiye'),
        ),
        migrations.AddField(
            model_name='kasafisislemleri',
            name='islem_sonucu_bakiye_cari',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Sonucu Bakiye'),
        ),
        migrations.AddField(
            model_name='kasafisislemleri',
            name='islem_sonucu_bakiye_ikinci_kasa',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Sonucu Bakiye'),
        ),
    ]
