# Generated by Django 4.1.2 on 2023-10-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0052_rename_slem_sonucu_bakiye_bankafisislemleri_islem_sonucu_bakiye_birinci_banka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankafisislemleri',
            name='birinci_banka_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birinci_banka_fis_islemleri_set', to='bilgideposu.banka', verbose_name='Birinci Kasa Bilgisi'),
        ),
        migrations.AlterField(
            model_name='bankafisislemleri',
            name='ikinci_banka_bilgisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinci_banka_fis_islemleri_set', to='bilgideposu.banka', verbose_name='İkinci Kasa Bilgisi'),
        ),
    ]
