# Generated by Django 4.1.2 on 2023-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0053_alter_bankafisislemleri_birinci_banka_bilgisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='bankafisislemleri',
            name='islem_doviz_cinsi',
            field=models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, verbose_name='İşlem Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='cari_kartislemleri_diger_bilgiler',
            name='bankadovizcinsi',
            field=models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='cari_kartislemleri_diger_bilgiler',
            name='digerdovizcinsi',
            field=models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='cari_kartislemleri_sube_bilgiler',
            name='subebilgileridovizcinsi',
            field=models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='gelirler',
            name='doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='giderler',
            name='doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi'),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='doviz_cinsi',
            field=models.CharField(blank=True, choices=[('', ''), ('TL', 'TL'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], default='', max_length=100, null=True, verbose_name='Döviz Cinsi'),
        ),
    ]
