# Generated by Django 4.1.2 on 2023-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0056_stok_alis_satis'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_kodlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozel_kod_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Kod 1')),
                ('ozel_kod_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Özel Kod 2')),
                ('grup_kod_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grup Kod 1')),
                ('grup_kod_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grup Kod 2')),
                ('grup_kod_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grup Kod 3')),
                ('gtipno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gtip No')),
                ('kalitekodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kalite Kodu')),
                ('barkod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barkod')),
                ('brimno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brim No')),
                ('alternatifstokkodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='alternatif stok kodu')),
                ('alternatifstokadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='alternatif stok adı')),
                ('alternatifstokkodu2', models.CharField(blank=True, max_length=100, null=True, verbose_name='alternatif stok kodu 2')),
                ('alternatifstokadi2', models.CharField(blank=True, max_length=200, null=True, verbose_name='alternatif stok adı 2')),
                ('alternatifstokkodu3', models.CharField(blank=True, max_length=100, null=True, verbose_name='alternatif stok kodu 3')),
                ('alternatifstokadi3', models.CharField(blank=True, max_length=200, null=True, verbose_name='alternatif stok adı 3')),
                ('yazarkasadepartman', models.CharField(blank=True, max_length=200, null=True, verbose_name='yazarkasadepartmani')),
                ('tazeurunkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='tazeurunkodu')),
                ('plukodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='plu kodu')),
                ('reyon', models.CharField(blank=True, max_length=200, null=True, verbose_name='reyon')),
                ('raf1', models.CharField(blank=True, max_length=100, null=True, verbose_name='raf 1')),
                ('raf2', models.CharField(blank=True, max_length=200, null=True, verbose_name='raf 2 ')),
                ('raf3', models.CharField(blank=True, max_length=200, null=True, verbose_name='raf 3 ')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_karti_bilgisi_kodlar_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
