# Generated by Django 4.1.2 on 2023-10-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0057_stok_kodlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_detaylari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametreadi1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paremetre Adı 1')),
                ('paremetredegeri1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Parametre Değeri 1')),
                ('parametreadi2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paremetre Adı 2')),
                ('paremetredegeri2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Parametre Değeri 2')),
                ('barkod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Barkod')),
                ('kalite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kalite')),
                ('detayozellikadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detaylı özellik adi')),
                ('varyant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varyant')),
                ('varyantkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varyant Kodu')),
                ('secili', models.CharField(blank=True, max_length=200, null=True, verbose_name='secili ? (E)')),
                ('varyantkodu2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Varyant Kodu2')),
                ('ozellik1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil1')),
                ('ozellik2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil2')),
                ('ozellik3', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil3')),
                ('ozellik4', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil4')),
                ('ozellik5', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil5')),
                ('ozellik6', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil6')),
                ('ozellik7', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil7')),
                ('ozellik8', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil8')),
                ('ozellik9', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil9')),
                ('ozellik10', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozelli10')),
                ('ozellik11', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil11')),
                ('ozellik12', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil12')),
                ('ozellik13', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil13')),
                ('ozellik14', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil14')),
                ('ozellik15', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil15')),
                ('ozellik16', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil16')),
                ('ozellik17', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil17')),
                ('ozellik18', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil18')),
                ('ozellik19', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil19')),
                ('ozellik20', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil20')),
                ('ozellik21', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil21')),
                ('ozellik22', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil22')),
                ('ozellik23', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil23')),
                ('ozellik24', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil24')),
                ('ozellik25', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil25')),
                ('ozellik26', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil26')),
                ('ozellik27', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil27')),
                ('ozellik28', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil28')),
                ('ozellik29', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil29')),
                ('ozellik30', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil30')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_karti_bilgisi_detaylari_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
