# Generated by Django 4.1.2 on 2023-10-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0059_stok_recetesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_muhasabe_kodlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_muh_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grup Muh Kodu')),
                ('uretime_sevk_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Üretime Sevk H. Kodu')),
                ('uretime_sarf_h_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Üretim Sarf H. Kodu')),
                ('uretime_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Üretim Hesap Kodu')),
                ('depo_s_fazlasi_h_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Depo S. Fazlası H. Kodu')),
                ('depo_s_eksikligi_h_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Depo S. Eksiği H. Kodu')),
                ('sarf_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sarf Hesap Kodu')),
                ('fire_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fire Hesap Kodu')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_muhasebekodlari_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
