# Generated by Django 4.1.2 on 2023-10-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0060_stok_muhasabe_kodlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_muhasebe_kodlari_evraklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_turu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Evrak Türü')),
                ('kdv_orani', models.CharField(blank=True, max_length=20, null=True, verbose_name='KDV Oranı')),
                ('tevkifat_orani', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tevkifat Oranı')),
                ('stok_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Hesap Kodu')),
                ('kdv_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='KDV Hesap Kodu')),
                ('tevkifat_hesap_kodu1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tevkifat Hesap Kodu 1')),
                ('tevkifat_hesap_kodu2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tevkifat Hesap Kodu 2')),
                ('otv_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='ÖTV Hesap Kodu')),
                ('otv_tescilb_hesap_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='ÖTV (Tescil B) Hesap Kodu')),
                ('evrak_bagli_birim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sevrak_bagli_birim_set', to='bilgideposu.stok_muhasabe_kodlari', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
