# Generated by Django 4.1.2 on 2023-10-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0061_stok_muhasebe_kodlari_evraklar'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_iliskili_gider_gelir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_ekle_gider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gider Ekle')),
                ('gider_orani', models.FloatField(blank=True, null=True, verbose_name='Gider Oranı')),
                ('o_ekle_gelir', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gider Ekle')),
                ('gelir_orani', models.FloatField(blank=True, null=True, verbose_name='Gider Oranı')),
                ('gelir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.gelirler', verbose_name='Gelir')),
                ('gider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.giderler', verbose_name='Gider')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_iliskili_gider_gelir_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
