# Generated by Django 4.1.2 on 2023-10-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0062_stok_iliskili_gider_gelir'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_diger_kismi_otv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otv_orani', models.FloatField(blank=True, null=True, verbose_name='ÖTV Oranı')),
                ('otv_brim_fiyati', models.FloatField(blank=True, null=True, verbose_name='ÖTV Brim Fiyatı')),
                ('otv_tahsil_orani', models.FloatField(blank=True, null=True, verbose_name='ÖTV Tahsil Oranı')),
                ('otv_tecil_orani', models.FloatField(blank=True, null=True, verbose_name='ÖTV Tecil Oranı')),
                ('mera_fonu_orani', models.FloatField(blank=True, null=True, verbose_name='Mera Fonu Oranı')),
                ('fire_orani', models.FloatField(blank=True, null=True, verbose_name='Fire Oranı')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_diger_kismi_otv_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
