# Generated by Django 4.1.2 on 2023-10-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0064_stok_diger_kismi_agirliklar'),
    ]

    operations = [
        migrations.CreateModel(
            name='stok_diger_birim_durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.CharField(blank=True, max_length=10, null=True, verbose_name='Birim No')),
                ('en', models.FloatField(blank=True, null=True, verbose_name='En Ölçüsü')),
                ('en_birimi', models.CharField(max_length=20, verbose_name='En Birimi')),
                ('boy', models.FloatField(blank=True, null=True, verbose_name='Boy Ölçüsü')),
                ('boy_birimi', models.CharField(max_length=20, verbose_name='Boy Birimi')),
                ('yukseklik', models.FloatField(blank=True, null=True, verbose_name='Yükseklik Ölçüsü')),
                ('yukseklik_birimi', models.CharField(max_length=20, verbose_name='Boy Birimi')),
                ('ebat_birimi', models.CharField(max_length=20, verbose_name='Ebat Birimi')),
                ('hacim', models.FloatField(blank=True, null=True, verbose_name='Hacim Ölçüsü')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_diger_birim_durumu_set', to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
            ],
        ),
    ]
