# Generated by Django 4.1.2 on 2023-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0065_stok_diger_birim_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok_alis_satis',
            name='satis_dovizcinsi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secilen Döviz Seçeneği'),
        ),
    ]
