# Generated by Django 4.1.2 on 2023-10-25 08:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0066_stok_alis_satis_satis_dovizcinsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='dilekceler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilekce', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Dilekçe Metni')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
