# Generated by Django 4.1.2 on 2023-10-26 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0069_siparisislem_durumlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='kayit_tarihi',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
