# Generated by Django 4.1.2 on 2023-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0070_siparisislem_durumlari_kayit_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok_diger_kismi_otv',
            name='otv_brim_no',
            field=models.FloatField(blank=True, null=True, verbose_name='ÖTV Brim Fiyatı'),
        ),
    ]
