# Generated by Django 4.1.2 on 2023-10-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0072_alter_stok_diger_kismi_otv_otv_brim_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='siparis_olustur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tur', models.CharField(choices=[('', ''), ('Alınan Sipariş', 'Alınan Sipariş'), ('Verilen Sipariş', 'Verilen Sipariş'), ('Alınan Teklif', 'Alınan Teklif'), ('Verilen Teklif', 'Verilen Teklif')], default='', max_length=200, verbose_name='Sipariş Türü')),
                ('siparis_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sipariş No')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('depo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Depo Adı')),
                ('ent_kodu', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=20, verbose_name='Entegrasyon Kodu')),
                ('kdv_durumu', models.CharField(choices=[('Hariç', 'Hariç'), ('Dahil', 'Dahil')], default='Hariç', max_length=200, verbose_name='KDV Durumu')),
                ('ozel_kod1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod')),
                ('ozel_kod2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod 2')),
                ('islem_doviz_cinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='İşlem Döviz Cinsi')),
                ('satici', models.CharField(blank=True, max_length=200, null=True, verbose_name='SAtıcı')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('miktar', models.FloatField(blank=True, default=1, null=True, verbose_name='Miktar')),
                ('kalan_miktar', models.FloatField(blank=True, default=1, null=True, verbose_name='Miktar')),
                ('birim', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birim')),
                ('birim_fiyat_tl', models.FloatField(blank=True, default=1, null=True, verbose_name='Birim Fiyatı TL')),
                ('birim_fiyat_dvz', models.FloatField(blank=True, default=1, null=True, verbose_name='Birim Fiyatı Döviz')),
                ('indirim_yuzdesi', models.FloatField(blank=True, default=0, null=True, verbose_name='İndirim Yüzdesi')),
                ('indirim_tutari_tl', models.FloatField(blank=True, default=0, null=True, verbose_name='İndirim Tutarı TL')),
                ('kdv_yuzdesi', models.FloatField(blank=True, default=0, null=True, verbose_name='KDV Yüzdesi')),
                ('kdv_tutari_tl', models.FloatField(blank=True, default=0, null=True, verbose_name='KDV Tutarı TL')),
                ('otv_yuzdesi', models.FloatField(blank=True, default=0, null=True, verbose_name='ÖTV Yüzdesi')),
                ('otv_tutari_tl', models.FloatField(blank=True, default=0, null=True, verbose_name='ÖTV Tutarı TL')),
                ('teslim_sekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teslim Şekli')),
                ('durumu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Durum')),
                ('indirim1', models.FloatField(blank=True, null=True, verbose_name='İndirim 1')),
                ('indirim2', models.FloatField(blank=True, null=True, verbose_name='İndirim 2')),
                ('indirim3', models.FloatField(blank=True, null=True, verbose_name='İndirim 3')),
                ('ozelkod1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod')),
                ('ozelkod2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod 2')),
                ('departman', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departman')),
                ('satir_aciklamasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Satır Açıklaması')),
                ('serino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seri No')),
                ('s_brim', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serbest Brim')),
                ('s_miktar', models.FloatField(blank=True, default=1, null=True, verbose_name='Serbest Miktar')),
                ('alternatifstokkodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='alternatif stok kodu')),
                ('alternatifstokadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='alternatif stok adı')),
                ('kalite', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kalite')),
                ('ozellik1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil1')),
                ('ozellik2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil2')),
                ('ozellik3', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil3')),
                ('ozellik4', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil4')),
                ('ozellik5', models.CharField(blank=True, max_length=200, null=True, verbose_name='ozellil5')),
                ('ana_miktar', models.FloatField(blank=True, default=1, null=True, verbose_name='Ana Miktar')),
                ('ana_birim_fiyat_tl', models.FloatField(blank=True, default=1, null=True, verbose_name='Ana Birim Fiyatı TL')),
                ('ana_birim_fiyat_dvz', models.FloatField(blank=True, default=1, null=True, verbose_name='Ana Birim Fiyatı Döviz')),
                ('parti_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Parti Kodu')),
                ('son_kullanim_tarihi', models.DateField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('cari_unvan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.cari_kartlar', verbose_name='Cari Unvan Bilgisi')),
                ('grup_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.siparisislem_durumlari', verbose_name='Grup Kodu')),
                ('stok_karti_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.stok_kartlar', verbose_name='Stok Kartı Bilgisi')),
                ('sube_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sube', verbose_name='Gelir Bilgisi')),
            ],
        ),
    ]
