# Generated by Django 4.1.2 on 2023-10-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0074_remove_siparis_olustur_cari_unvan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis_olustur',
            name='tip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tip'),
        ),
    ]
