# Generated by Django 4.1.2 on 2023-10-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0075_siparis_olustur_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis_olustur',
            name='teslim_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
    ]
