# Generated by Django 4.1.2 on 2023-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0077_remove_siparis_olustur_teslim_tarih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok_birim_alis_satis_birimi',
            name='stokmiktari',
            field=models.FloatField(blank=True, null=True, verbose_name='Stok Miktarı'),
        ),
    ]
