# Generated by Django 4.1.2 on 2023-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0079_siparis_olustur_stoktutari'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='aktif_pasif',
            field=models.BooleanField(default=False, verbose_name='Aktif Pasif Olayı'),
        ),
    ]
