# Generated by Django 4.1.2 on 2023-11-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0080_siparisislem_durumlari_aktif_pasif'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='indirim_tutari',
            field=models.FloatField(blank=True, null=True, verbose_name='İndirim Tutarı TL'),
        ),
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='kdv_tutari',
            field=models.FloatField(blank=True, null=True, verbose_name='KDV Tutarı TL'),
        ),
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='otv_tutari',
            field=models.FloatField(blank=True, null=True, verbose_name='Ötv Tutarı TL'),
        ),
    ]
