# Generated by Django 4.1.2 on 2023-11-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0081_siparisislem_durumlari_indirim_tutari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='genel_tutari',
            field=models.FloatField(blank=True, null=True, verbose_name='Genel Tutarı TL'),
        ),
    ]
