# Generated by Django 4.1.2 on 2023-11-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0082_siparisislem_durumlari_genel_tutari'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='iptaledildi',
            field=models.BooleanField(default=False, verbose_name='İptal Edildi'),
        ),
    ]
