# Generated by Django 4.1.2 on 2023-11-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0083_siparisislem_durumlari_iptaledildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='silinme_bilgisi',
            field=models.BooleanField(default=False, verbose_name='Sİpariş Silme Durumu'),
        ),
    ]
