# Generated by Django 4.1.2 on 2023-11-03 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0084_siparisislem_durumlari_silinme_bilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='irsaliyeislem_durumlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_tur', models.CharField(choices=[('', ''), ('Satış İrsaliyesi', 'Satış İrsaliyesi'), ('Satış İade İrsaliyesi', 'Satış İade İrsaliyesi'), ('Alış İrsaliyesi', 'Alış İrsaliyesi'), ('Alış İade İrsaliyesi', 'Alış İade İrsaliyesi'), ('Konsinye Çıkış İrsaliyesi', 'Konsinye Çıkış İrsaliyesi'), ('Konsinye Çıkış İade İrsaliyesi', 'Konsinye Çıkış İade İrsaliyesi'), ('Konsinye Giriş İrsaliyesi', 'Konsinye Giriş İrsaliyesi'), ('Konsinye Giriş İade İrsaliyesi', 'Konsinye Giriş İade İrsaliyesi'), ('Depo Sayım Fazlası', 'Depo Sayım Fazlası'), ('Depo Sayım Eksikliği', 'Depo Sayım Eksikliği'), ('Depo Transfer Fişi', 'Depo Transfer Fişi'), ('Üretimden Giriş Fişi', 'Üretimden Giriş Fişi'), ('Üretim Sevk Fişi', 'Üretim Sevk Fişi'), ('Üretim Sevk iade Fişi', 'Üretim Sevk iade Fişi'), ('Fire Fişi', 'Fire Fişi'), ('Sarf Fişi', 'Sarf Fişi'), ('Açılış Fişi', 'Açılış Fişi'), ('Stok (Depo) Sayım Fişleri', 'Stok (Depo) Sayım Fişleri')], default='', max_length=200, verbose_name='Sipariş Türü')),
                ('kayit_tarihi', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('depo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Depo Adı')),
                ('ent_kodu', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=20, verbose_name='Entegrasyon Kodu')),
                ('kdv_durumu', models.CharField(choices=[('Hariç', 'Hariç'), ('Dahil', 'Dahil')], default='Hariç', max_length=200, verbose_name='KDV Durumu')),
                ('siparis_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sipariş No')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('teslim_sekli', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teslim Şekli')),
                ('satici', models.CharField(blank=True, max_length=200, null=True, verbose_name='SAtıcı')),
                ('islem_doviz_cinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='İşlem Döviz Cinsi')),
                ('ozel_kod1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod')),
                ('ozel_kod2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod 2')),
                ('departman', models.CharField(blank=True, max_length=200, null=True, verbose_name='departman')),
                ('onay', models.BooleanField(default=False, verbose_name='Sipariş Onaylandı')),
                ('gunluk_kur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Günlük Kur')),
                ('uygun_kur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Uygun Kur')),
                ('faturaya_aktar', models.BooleanField(default=False, verbose_name='Faturaya Aktarıldı')),
                ('tutar_doviz', models.FloatField(blank=True, null=True, verbose_name='Tutar Döviz')),
                ('tutar_tl', models.FloatField(blank=True, null=True, verbose_name='Tutar TL')),
                ('aktif_pasif', models.BooleanField(default=False, verbose_name='Aktif Pasif Olayı')),
                ('otv_tutari', models.FloatField(blank=True, null=True, verbose_name='Ötv Tutarı TL')),
                ('kdv_tutari', models.FloatField(blank=True, null=True, verbose_name='KDV Tutarı TL')),
                ('indirim_tutari', models.FloatField(blank=True, null=True, verbose_name='İndirim Tutarı TL')),
                ('genel_tutari', models.FloatField(blank=True, null=True, verbose_name='Genel Tutarı TL')),
                ('iptaledildi', models.BooleanField(default=False, verbose_name='İptal Edildi')),
                ('silinme_bilgisi', models.BooleanField(default=False, verbose_name='Sİpariş Silme Durumu')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('cari_unvan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.cari_kartlar', verbose_name='Cari Unvan Bilgisi')),
                ('sube_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sube', verbose_name='Şube Bilgisi')),
            ],
        ),
    ]
