# Generated by Django 4.1.2 on 2023-11-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0086_irsaliye_olustur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irsaliyeislem_durumlari',
            name='teslim_sekli',
        ),
    ]
