# Generated by Django 4.1.2 on 2023-11-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0087_remove_irsaliyeislem_durumlari_teslim_sekli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irsaliye_olustur',
            name='grup_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.irsaliyeislem_durumlari', verbose_name='Grup Kodu'),
        ),
    ]
