# Generated by Django 4.1.2 on 2023-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0089_fatura_durumlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparisislem_durumlari',
            name='irsaliye_durumu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İrsaliye Teslim Durumu'),
        ),
    ]
