# Generated by Django 4.1.2 on 2023-11-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0091_alter_fatura_durumlari_siparis_tur_fatura_olustur'),
    ]

    operations = [
        migrations.CreateModel(
            name='cek_senet_durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodro_tarihi', models.DateField(blank=True, null=True, verbose_name='Kayıt Tarihi')),
                ('bodro_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bodro No')),
                ('ent_kodu', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=20, verbose_name='Entegrasyon Kodu')),
                ('saat', models.TimeField(blank=True, null=True, verbose_name='Saat')),
                ('devir_mi', models.BooleanField(default=False, verbose_name='Devir Mi ? ')),
                ('islem_doviz_cinsi', models.CharField(choices=[('', ''), ('TL', 'TL'), ('Euro', '£'), ('Dolar', '$')], default='', max_length=100, verbose_name='İşlem Döviz Cinsi')),
                ('ozel_kod1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod')),
                ('ozel_kod2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Özel Kod 2')),
                ('departman', models.CharField(blank=True, max_length=200, null=True, verbose_name='departman')),
                ('kampkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kamp Kod')),
                ('muh_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='muh. Kod 2')),
                ('aciklama', models.CharField(blank=True, max_length=200, null=True, verbose_name='açıklama')),
                ('tahsilati_ismeli_yapan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tahsilati İşlemi Yapan')),
                ('cari_unvan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.cari_kartlar', verbose_name='Cari Unvan Bilgisi')),
                ('sube_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sube', verbose_name='Şube Bilgisi')),
            ],
        ),
    ]
