# Generated by Django 4.1.2 on 2023-12-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_sgk_bolgecalisma_mudurlukleri_iskurbilgileri'),
        ('bilgideposu', '0095_genel_muhasebe'),
    ]

    operations = [
        migrations.CreateModel(
            name='genel_muhasebe_fis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_tarihi', models.DateField(blank=True, null=True, verbose_name='Evrak Tarihi')),
                ('bt_turu', models.CharField(blank=True, max_length=200, null=True, verbose_name='BT Türü')),
                ('vergi_numarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vergi Nuımarası')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('aciklama8belgesi', models.TextField(blank=True, null=True, verbose_name='aciklama8belgesi')),
                ('borc', models.FloatField(default=0, verbose_name='Borç Bilgisi')),
                ('alacak_bilgisi', models.FloatField(default=0, verbose_name='Borç Bilgisi')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('bagli_oldugufis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.genel_muhasebe')),
                ('hesap_plani_secim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.hesapplanlari')),
            ],
        ),
    ]
