# Generated by Django 4.1.2 on 2023-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0096_genel_muhasebe_fis'),
    ]

    operations = [
        migrations.AddField(
            model_name='genel_muhasebe',
            name='fis_turu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='yevmiye No'),
        ),
    ]
