# Generated by Django 4.1.2 on 2023-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0097_genel_muhasebe_fis_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='genel_muhasebe_fis',
            name='evrak_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fiş No'),
        ),
    ]
