# Generated by Django 4.1.2 on 2023-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0098_genel_muhasebe_fis_evrak_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesapplanlari',
            name='alacak_toplam',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Alacak Toplam'),
        ),
        migrations.AlterField(
            model_name='hesapplanlari',
            name='bakiye_toplam',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bakiye Toplam'),
        ),
        migrations.AlterField(
            model_name='hesapplanlari',
            name='borc_toplam',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Borç Toplam'),
        ),
    ]
