# Generated by Django 4.1.2 on 2024-01-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_sgk_bilgileri_personel_6116645yararlanmiyorsayenikanun'),
        ('bilgideposu', '0102_alter_hesapplanlari_kdv_orani'),
    ]

    operations = [
        migrations.CreateModel(
            name='musteri_cari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cari Adı')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
        migrations.CreateModel(
            name='musteri_cari_fis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_tarihi', models.DateField(blank=True, null=True, verbose_name='evrak Tarihi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('alacak', models.FloatField(default=0, verbose_name='Alacak ')),
                ('borc', models.FloatField(default=0, verbose_name='Borc ')),
                ('bagli_oldugu_cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.musteri_cari')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
