# Generated by Django 4.1.2 on 2024-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0103_musteri_cari_musteri_cari_fis'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri_cari',
            name='sininme_bilgisi',
            field=models.BooleanField(default=False),
        ),
    ]
