# Generated by Django 4.1.2 on 2024-01-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_sgk_bilgileri_personel_6116645yararlanmiyorsayenikanun'),
        ('bilgideposu', '0106_musavir_stok_stok_kodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='musavir_stok_fisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evrak_tarihi', models.DateField(blank=True, null=True, verbose_name='Evrak Tarihi')),
                ('donem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dönem Başı Veya Dönem İçi')),
                ('iademi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İademi ? ')),
                ('evrak_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='evrak No')),
                ('evrak_aciklama', models.CharField(blank=True, max_length=200, null=True, verbose_name='Evrak Açıklama')),
                ('giris_miktari', models.FloatField(default=0, verbose_name='Giriş Miktari')),
                ('cikis_miktari', models.FloatField(default=0, verbose_name='Çıkış Miktari')),
                ('giris_birim_fiyati', models.FloatField(default=0, verbose_name='Giriş Brm Fiyatı')),
                ('giris_fiyati', models.FloatField(default=0, verbose_name='Giriş Fiyatı')),
                ('cikis_birim_fiyati', models.FloatField(default=0, verbose_name='Çıkış Brm Fiyatı')),
                ('cikis_fiyati', models.FloatField(default=0, verbose_name='Çıkış Fiyatı')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('bagli_oldugu_stok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.musavir_stok')),
            ],
        ),
    ]
