# Generated by Django 4.1.2 on 2024-01-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0107_musavir_stok_fisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='musavir_stok',
            name='ticari',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Envanter yönetimi'),
        ),
    ]
