# Generated by Django 4.1.2 on 2024-01-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0108_musavir_stok_ticari'),
    ]

    operations = [
        migrations.CreateModel(
            name='amortisman_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N3', models.CharField(blank=True, max_length=200, null=True, verbose_name='N3')),
                ('N4', models.CharField(blank=True, max_length=200, null=True, verbose_name='N4')),
                ('amortismana_tabi_olan_ikstisidai_kiymet', models.CharField(blank=True, max_length=400, null=True, verbose_name='N4')),
                ('faydali_omur', models.BigIntegerField(default=0, verbose_name='Faydalı Ömür')),
                ('amortisman_orani', models.FloatField(default=0, verbose_name='Amortisman Oranı')),
                ('defter_beyan_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Defter Beyan Kodu')),
            ],
        ),
        migrations.CreateModel(
            name='sabit_kiyem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabit_kiyemet_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='sabit kıymet kodu')),
                ('sabit_kiymet_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='sabit kıymet kodu')),
            ],
        ),
    ]
