# Generated by Django 4.1.2 on 2024-01-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0109_amortisman_bilgileri_sabit_kiyem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genel_Muhasebe_cari_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Cari Adı')),
                ('vergi_tc_kimlikno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Tc Kimlik No')),
                ('vergi_dairesi_bilgisi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vergi Dairesi Bilgisi')),
                ('ulke_kodu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ülke Kodu')),
                ('firma_unvani', models.CharField(blank=True, max_length=600, null=True, verbose_name='Firma unvanı Adı')),
                ('telefon_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1 ')),
                ('telefon_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1 ')),
                ('telefon_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1 ')),
                ('telefon_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 1 ')),
                ('adres_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres ')),
                ('adres_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 1 ')),
                ('adres_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 1 ')),
                ('adres_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 1 ')),
                ('fax_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax 1 ')),
                ('fax_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax 2 ')),
                ('cep_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep 1 ')),
                ('cep_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep 2 ')),
                ('email_1', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email ')),
                ('email_2', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email 1 ')),
                ('web_adresi', models.CharField(blank=True, max_length=400, null=True, verbose_name='web 1 ')),
                ('yetkili', models.CharField(blank=True, max_length=400, null=True, verbose_name='Yetkili ')),
                ('gorevi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Görevi ')),
                ('bilgi_notu', models.CharField(blank=True, max_length=400, null=True, verbose_name='Bilgi Notu ')),
                ('il', models.CharField(blank=True, max_length=400, null=True, verbose_name='il ')),
                ('ilce', models.CharField(blank=True, max_length=400, null=True, verbose_name='İlçe ')),
                ('posta_kodu', models.CharField(blank=True, max_length=400, null=True, verbose_name='Posta Kodu ')),
                ('ulke', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ülke ')),
                ('alis_muh_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alis_muhtasar_kodu', to='bilgideposu.hesapplanlari')),
                ('satis_muh_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satis_muhtasar_kodu', to='bilgideposu.hesapplanlari')),
            ],
        ),
    ]
