# Generated by Django 4.1.2 on 2024-01-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0110_genel_muhasebe_cari_bilgileri'),
    ]

    operations = [
        migrations.CreateModel(
            name='demirbaslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='sabit_kiyem',
        ),
    ]
