# Generated by Django 4.1.2 on 2024-01-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0111_demirbaslar_delete_sabit_kiyem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demirbaslar',
        ),
    ]
