# Generated by Django 4.1.2 on 2024-01-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0113_amortisman_bilgileri_n1_amortisman_bilgileri_n2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevkifat_tur_kodu',
            name='tevkifat_orani',
            field=models.CharField(blank=True, choices=[('', ''), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('7/10', '7/10'), ('9/10', '9/10'), ('10/10', '10/10')], default='', max_length=100, null=True, verbose_name='Tevkifat Orani'),
        ),
    ]
