# Generated by Django 4.1.2 on 2024-01-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0114_alter_tevkifat_tur_kodu_tevkifat_orani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevkifat_tur_kodu',
            name='iliskili_kdv_hesap_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iliskili_kdv_hesap_kodular', to='bilgideposu.tevkifat_tur_kodu', verbose_name='İlişkili KDV Hesap Kodu'),
        ),
        migrations.AlterField(
            model_name='tevkifat_tur_kodu',
            name='stopaj_hesap_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopaj_hesap_kodular', to='bilgideposu.tevkifat_tur_kodu', verbose_name='Stopaj Hesap Kodu'),
        ),
        migrations.AlterField(
            model_name='tevkifat_tur_kodu',
            name='tevkifat_hesap_kodu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tevkifat_hesap_kodular', to='bilgideposu.tevkifat_tur_kodu', verbose_name='Tevkifat KDV Hesap Kodu'),
        ),
    ]
