# Generated by Django 4.1.2 on 2024-01-09 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_sgk_bilgileri_personel_6116645yararlanmiyorsayenikanun'),
        ('bilgideposu', '0115_alter_tevkifat_tur_kodu_iliskili_kdv_hesap_kodu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='firma_ayarlari_ayar_kisimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damga_vergisi_5033sk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Damga Vergisi ,5033 Sk')),
                ('muhasabe_odemesi_gelir_vergisi_kesinti_orani', models.FloatField(default=0, verbose_name='Gelir Ödemesi Vergi Kesintisi')),
                ('kira_odemesi_gelir_vergisi_kesinti_orani', models.FloatField(default=0, verbose_name='Kira Ödemesi Vergi Kesintisi')),
                ('kdv_beyannamesi_damga_vergisi', models.FloatField(default=0, verbose_name='KDV Beyannamesi Damga Vergisi')),
                ('gecici_vergi_beyannamesi_damga_vergisi', models.FloatField(default=0, verbose_name='Gecici Vergi Beyannamesi Damga Vergisi')),
                ('gecici_vergi_orani_kurumlar', models.FloatField(default=0, verbose_name='Gecici Vergi Orani Kurumlar')),
                ('gecici_vergi_orani_gercek_kisiler', models.FloatField(default=0, verbose_name='Gecici Vergi Orani Gerçek Kişiler')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
