# Generated by Django 4.1.2 on 2024-01-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_sgk_bilgileri_personel_6116645yararlanmiyorsayenikanun'),
        ('bilgideposu', '0116_firma_ayarlari_ayar_kisimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='firma_ayarlari_smm_ymm_sm_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=400, null=True, verbose_name='ad')),
                ('soyad', models.CharField(blank=True, max_length=400, null=True, verbose_name='soyad')),
                ('musavir_turu', models.CharField(blank=True, max_length=400, null=True, verbose_name='Müşavir Türü')),
                ('kayitliolduguoda', models.CharField(blank=True, max_length=400, null=True, verbose_name='Kayıtlı oldugu Oda')),
                ('odasicilno', models.CharField(blank=True, max_length=400, null=True, verbose_name='Oda Sicil No')),
                ('muhur_numarasi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Mühür Numarası')),
                ('baslama_tarihi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Başlama Tarihi')),
                ('ortakli_unvan', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ortak Unvanlı')),
                ('sirket_unvan', models.CharField(blank=True, max_length=400, null=True, verbose_name='Şirket Unvanlı')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Vergi Dairesi')),
                ('vergi_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='Vergi No')),
                ('ticari_sicil_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ticari Sicili No')),
                ('vergi_kimlik_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='Vergi Kimlik No')),
                ('tc_kimlik_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='Tc Kimlik No')),
                ('goreve_baslama_tarihi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Görev Başlama Tarihi')),
                ('isyeri_adresi', models.CharField(blank=True, max_length=400, null=True, verbose_name='İşeri Adresi')),
                ('fax', models.CharField(blank=True, max_length=400, null=True, verbose_name='fax')),
                ('eposta', models.CharField(blank=True, max_length=400, null=True, verbose_name='E-Posta')),
                ('arac_plaka_no', models.CharField(blank=True, max_length=400, null=True, verbose_name='Araç Plaka No')),
                ('cinsiyet', models.CharField(blank=True, max_length=400, null=True, verbose_name='Cinsiyet')),
                ('uyrugu', models.CharField(blank=True, max_length=400, null=True, verbose_name='Uyruğu')),
                ('baba_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Baba Adı')),
                ('anne_adi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Anne Adı')),
                ('dogum_yeri', models.CharField(blank=True, max_length=400, null=True, verbose_name='Doğum Yeri')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=400, null=True, verbose_name='Doğum Tarihi')),
                ('nufusa_kayitli_oldugu_yer', models.CharField(blank=True, max_length=400, null=True, verbose_name='Nüfusta Kayıtlı Olduğu Yer')),
                ('ikametgah_adresi', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah Adresi')),
                ('ikametgah_bulvar', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah bulvar')),
                ('ikametgah_cadde', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah Cadde')),
                ('ikametgah_sokak', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah Sokak')),
                ('ikametgah_ic_kapi', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah İç Kapı')),
                ('ikametgah_dis_kapi', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah Dış Kapı')),
                ('ikametgah_mahalle_koy', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah Mahalle Köy')),
                ('ikametgah_ilce', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah İlçe')),
                ('ikametgah_il', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah İl')),
                ('ikametgah_posta_kodu', models.CharField(blank=True, max_length=400, null=True, verbose_name='İkametgah Posta Kodu')),
                ('cep_telefonu', models.CharField(blank=True, max_length=400, null=True, verbose_name='Cep Telefonu')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
