# Generated by Django 4.1.2 on 2024-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0117_firma_ayarlari_smm_ymm_sm_bilgileri'),
    ]

    operations = [
        migrations.CreateModel(
            name='urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ürün Kodu')),
                ('grup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grup Kodu')),
                ('urun_adi', models.CharField(blank=True, max_length=200, null=True, verbose_name='ürün Adları')),
                ('tutar', models.FloatField(default=0, verbose_name='Tutarı')),
                ('birimi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birimi')),
            ],
        ),
    ]
