# Generated by Django 4.1.2 on 2024-01-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0118_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayanak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
            ],
        ),
    ]
