# Generated by Django 4.1.2 on 2024-01-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0121_matrah_bildirimi_tevkifatuygulanmayanislemler'),
    ]

    operations = [
        migrations.CreateModel(
            name='matrah_bildirimi_kismi_tevkifatuygulanmayanislemler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrah', models.FloatField(default=0, verbose_name='Matrah')),
                ('kdv', models.FloatField(default=0, verbose_name='KDV')),
                ('vergi', models.FloatField(default=0, verbose_name='Vergi')),
                ('tevkifatorani', models.CharField(blank=True, max_length=20, null=True, verbose_name='tevkifatorani')),
                ('matrah1', models.FloatField(default=0, verbose_name='Matrah')),
                ('kdv1', models.FloatField(default=0, verbose_name='KDV')),
                ('vergi1', models.FloatField(default=0, verbose_name='Vergi')),
                ('tevkifatorani1', models.CharField(blank=True, max_length=20, null=True, verbose_name='tevkifatorani')),
                ('matrah2', models.FloatField(default=0, verbose_name='Matrah')),
                ('kdv2', models.FloatField(default=0, verbose_name='KDV')),
                ('vergi2', models.FloatField(default=0, verbose_name='Vergi')),
                ('tevkifatorani2', models.CharField(blank=True, max_length=20, null=True, verbose_name='tevkifatorani')),
                ('matrah3', models.FloatField(default=0, verbose_name='Matrah')),
                ('kdv3', models.FloatField(default=0, verbose_name='KDV')),
                ('vergi3', models.FloatField(default=0, verbose_name='Vergi')),
                ('tevkifatorani3', models.CharField(blank=True, max_length=20, null=True, verbose_name='tevkifatorani')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('islem_turu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_turu', to='bilgideposu.tevkifat_tur_kodu')),
                ('islem_turu1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_turu1', to='bilgideposu.tevkifat_tur_kodu')),
                ('islem_turu2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_turu2', to='bilgideposu.tevkifat_tur_kodu')),
                ('islem_turu3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_turu3', to='bilgideposu.tevkifat_tur_kodu')),
            ],
        ),
    ]
