# Generated by Django 4.1.2 on 2024-01-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0122_matrah_bildirimi_kismi_tevkifatuygulanmayanislemler'),
    ]

    operations = [
        migrations.CreateModel(
            name='matrah_bildirimi_digerislemleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrah1', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi1', models.FloatField(default=0, verbose_name='Vergi')),
                ('matrah2', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi2', models.FloatField(default=0, verbose_name='Vergi')),
                ('matrah3', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi3', models.FloatField(default=0, verbose_name='Vergi')),
                ('matrah4', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi4', models.FloatField(default=0, verbose_name='Vergi')),
                ('matrah5', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi5', models.FloatField(default=0, verbose_name='Vergi')),
                ('matrah6', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi6', models.FloatField(default=0, verbose_name='Vergi')),
                ('matrah7', models.FloatField(default=0, verbose_name='Matrah')),
                ('vergi7', models.FloatField(default=0, verbose_name='Vergi')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
