# Generated by Django 4.1.2 on 2024-01-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0123_matrah_bildirimi_digerislemleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='matrah_bildirimi_istegebaglitamtevkifat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrah', models.FloatField(default=0, verbose_name='Matrah')),
                ('kdv', models.FloatField(default=0, verbose_name='KDV')),
                ('vergi', models.FloatField(default=0, verbose_name='Vergi')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('islem_turu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.tevkifat_tur_kodu')),
            ],
        ),
    ]
