# Generated by Django 4.1.2 on 2024-01-23 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0124_matrah_bildirimi_istegebaglitamtevkifat'),
    ]

    operations = [
        migrations.CreateModel(
            name='indirimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar1', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar2', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar3', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar4', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar5', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar6', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar7', models.FloatField(default=0, verbose_name='Tutar')),
                ('tutar8', models.FloatField(default=0, verbose_name='Tutar')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
