# Generated by Django 4.1.2 on 2024-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0127_matrah_bildirimi_digerislemleri_bilgi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirimler',
            name='bilgi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
        migrations.AddField(
            model_name='indirimler',
            name='bilgi8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi 1'),
        ),
    ]
