# Generated by Django 4.1.2 on 2024-01-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0128_indirimler_bilgi_indirimler_bilgi1_indirimler_bilgi2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='indirim_oncekidonem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirimoncekidonem1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama1', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar1', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama2', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar2', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama3', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar3', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama4', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar4', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama5', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar5', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama6', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar6', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama7', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar7', models.FloatField(default=0, verbose_name='Miktar')),
                ('indirimoncekidonem8', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlığı')),
                ('aciklama8', models.CharField(blank=True, max_length=400, null=True, verbose_name='Açıklama')),
                ('miktar8', models.FloatField(default=0, verbose_name='Miktar')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
