# Generated by Django 4.1.2 on 2024-01-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0129_indirim_oncekidonem'),
    ]

    operations = [
        migrations.CreateModel(
            name='sonuc_hesaplari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonucyazisi1', models.CharField(blank=True, max_length=200, null=True, verbose_name='sonuç yazısı')),
                ('sonuc1', models.FloatField(default=0, verbose_name='sonuctutarı')),
                ('sonuc2', models.FloatField(default=0, verbose_name='sonuctutarı')),
                ('sonucyazisi2', models.CharField(blank=True, max_length=200, null=True, verbose_name='sonuç yazısı')),
                ('sonuc3', models.FloatField(default=0, verbose_name='sonuctutarı')),
                ('sonucyazisi3', models.CharField(blank=True, max_length=200, null=True, verbose_name='sonuç yazısı')),
                ('sonuc4', models.FloatField(default=0, verbose_name='sonuctutarı')),
                ('sonucyazisi4', models.CharField(blank=True, max_length=200, null=True, verbose_name='sonuç yazısı')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
