# Generated by Django 4.1.2 on 2024-01-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0131_sonuc_hesaplari_digerbilgiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='kismi_istisna_durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istisnakismikdvistisnasecimihizmetveteslimtutari1', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimiyuklenilenkdv1', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimihizmetveteslimtutari2', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimiyuklenilenkdv2', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimihizmetveteslimtutari3', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimiyuklenilenkdv3', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimihizmetveteslimtutari4', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimiyuklenilenkdv4', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimihizmetveteslimtutari5', models.FloatField(default=0, verbose_name='tutar')),
                ('istisnakismikdvistisnasecimiyuklenilenkdv5', models.FloatField(default=0, verbose_name='tutar')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('istisna1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisna_1', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 1')),
                ('istisna2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisna_2', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 2')),
                ('istisna3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisna_3', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 3 ')),
                ('istisna4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisna_4', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 4')),
                ('istisna5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisna_5', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 5')),
            ],
        ),
    ]
