# Generated by Django 4.1.2 on 2024-01-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0132_kismi_istisna_durumu'),
    ]

    operations = [
        migrations.CreateModel(
            name='tam_istisnaa_durumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamistisnamalhizmeti1', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalbedeli1', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnayuklenilenkdv1', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalhizmeti2', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalbedeli2', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnayuklenilenkdv2', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalhizmeti3', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalbedeli3', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnayuklenilenkdv3', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalhizmeti4', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalbedeli4', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnayuklenilenkdv4', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalhizmeti5', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnamalbedeli5', models.FloatField(default=0, verbose_name='tutar')),
                ('tamistisnayuklenilenkdv5', models.FloatField(default=0, verbose_name='tutar')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('istisnaa1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisnaa_1', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 1')),
                ('istisnaa2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisnaa_2', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 2')),
                ('istisnaa3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisnaa_3', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 3 ')),
                ('istisnaa4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisnaa_4', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 4')),
                ('istisnaa5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istisnaa_5', to='bilgideposu.kdv_istisna_kodu', verbose_name='İstisna 5')),
            ],
        ),
    ]
