# Generated by Django 4.1.2 on 2024-01-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0134_istegebaglitamtevkifat_giren_islemler'),
    ]

    operations = [
        migrations.CreateModel(
            name='iade_hakki_digerislemleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilgi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('digeriadetamistisnamalhizmeti1', models.FloatField(default=0, verbose_name='Matrah')),
                ('digeriadekonuolankdv1', models.FloatField(default=0, verbose_name='Vergi')),
                ('bilgi2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('digeriadetamistisnamalhizmeti2', models.FloatField(default=0, verbose_name='Matrah')),
                ('digeriadekonuolankdv2', models.FloatField(default=0, verbose_name='Vergi')),
                ('bilgi3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('digeriadetamistisnamalhizmeti3', models.FloatField(default=0, verbose_name='Matrah')),
                ('digeriadekonuolankdv3', models.FloatField(default=0, verbose_name='Vergi')),
                ('bilgi4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('digeriadetamistisnamalhizmeti4', models.FloatField(default=0, verbose_name='Matrah')),
                ('digeriadekonuolankdv4', models.FloatField(default=0, verbose_name='Vergi')),
                ('bilgi5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('digeriadetamistisnamalhizmeti5', models.FloatField(default=0, verbose_name='Matrah')),
                ('digeriadekonuolankdv5', models.FloatField(default=0, verbose_name='Vergi')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
