# Generated by Django 4.1.2 on 2024-01-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_paketler'),
        ('bilgideposu', '0135_iade_hakki_digerislemleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='ihrac_kaydiyla_teslimler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(blank=True, max_length=200, null=True, verbose_name='İşlem Türüğ')),
                ('ihrac_kaydiyla_teslimler_tutar', models.FloatField(default=0, verbose_name='ihrac_kaydiyla_teslimler')),
                ('ihrackaydikdvorani', models.FloatField(default=0, verbose_name='KDV')),
                ('hesaplanantutar', models.FloatField(default=0, verbose_name='KDV')),
                ('bagli_oldugu_beyanname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilgideposu.kdv1_beyannamesi_bilgileri')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
            ],
        ),
    ]
