# Generated by Django 4.1.2 on 2024-01-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0136_ihrac_kaydiyla_teslimler'),
    ]

    operations = [
        migrations.CreateModel(
            name='gecicivergi_beyannamesi_inidimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.CharField(max_length=200, verbose_name='Açıklama')),
            ],
        ),
    ]
