# Generated by Django 4.1.2 on 2024-02-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilgideposu', '0138_iller_ilkodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='saglikhizmetindenfaydalananisletmeadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saglikhizmetindenfaydalananisletmeadi', models.CharField(max_length=200, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='saglikhizmetindenfaydalananisletmeturu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saglikhizmetindenfaydalananisletmeturu', models.CharField(max_length=200, verbose_name='Açıklama')),
            ],
        ),
    ]
