# Generated by Django 4.1.2 on 2023-06-18 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Referans_kodu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_dogrulama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hesap_turu',
            field=models.CharField(choices=[('muhasebeci', 'muhasebeci'), ('sirket', 'sirket'), ('admin1', 'admin1'), ('admin2', 'admin2'), ('admin3', 'admin3')], default='muhasebeci', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kullanicilar_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
