# Generated by Django 4.1.2 on 2023-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_status_customuser_referans_kodu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referans_olan_kod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
