# Generated by Django 4.1.2 on 2023-06-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_referans_olan_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='smmmok',
            field=models.FileField(blank=True, null=True, upload_to='companylogo/', verbose_name='Şirket Logosu'),
        ),
    ]
