# Generated by Django 4.1.2 on 2023-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_smmmok'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kullanici_silme_bilgisi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lisans_bitis_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Lisans Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefon_no',
            field=models.CharField(default=0, max_length=20, verbose_name='Telefon Numarası'),
            preserve_default=False,
        ),
    ]
