# Generated by Django 4.1.2 on 2023-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_kullanici_silme_bilgisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firma_adi',
            field=models.CharField(default=0, max_length=100, verbose_name='Firma Adı'),
            preserve_default=False,
        ),
    ]
