# Generated by Django 4.1.2 on 2023-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='tanitici_isim',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tanıtıcı Adı'),
        ),
    ]
