# Generated by Django 4.1.2 on 2023-06-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_firma_tanitici_isim'),
    ]

    operations = [
        migrations.CreateModel(
            name='adresler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=200, verbose_name='Adres')),
                ('mahhalle_koy', models.CharField(max_length=100, verbose_name='Mahalle Köy')),
                ('bulvar', models.CharField(max_length=100, verbose_name='Bulvar')),
                ('cadde', models.CharField(max_length=100, verbose_name='Cadde')),
                ('sokak', models.CharField(max_length=100, verbose_name='Sokak')),
                ('adaparselno', models.CharField(max_length=100, verbose_name='ADA Parsel No')),
                ('diskapino', models.CharField(max_length=10, verbose_name='Dış Kapı No')),
                ('ickapino', models.CharField(max_length=10, verbose_name='İç Kapı No')),
                ('posta_kodu', models.CharField(max_length=100, verbose_name='Posta Kodu')),
                ('semt', models.CharField(max_length=100, verbose_name='Semt')),
                ('ilce', models.CharField(max_length=100, verbose_name='İlçe')),
                ('il', models.CharField(choices=[('istanbul', 'istanbul'), ('Van', 'Van'), ('Ankara', 'Ankara'), ('Batman', 'Batman'), ('Mersin', 'Mersin')], default='Van', max_length=50, verbose_name='İl')),
            ],
        ),
    ]
