# Generated by Django 4.1.2 on 2023-06-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_vergi_dairesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube_adi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Adı')),
                ('sube_unvani', models.CharField(max_length=100, verbose_name='Şube Unvanı')),
                ('vergi_dairesi_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi Kodu')),
                ('vergi_numarasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Numarası')),
                ('sahis_ise_tc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Şahis İse Tc Kimlik Numarası')),
                ('email_adresi', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Şube Email Adresi ')),
                ('web_adresi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Web Adresi ')),
                ('telefon_numarasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Telefon Numarası ')),
                ('sube_defter_turu', models.CharField(blank=True, choices=[('Genel Muhasebe', 'Genel Muhasebe'), ('İşletme Defteri', 'İşletme Defteri')], default='Genel Muhasebe', max_length=100, null=True, verbose_name='Şube Defter Türü ')),
                ('kdv1', models.CharField(blank=True, choices=[('Aylık', 'Aylık'), ('Üç Aylık', 'Üç Aylık')], default='Aylık', max_length=100, null=True, verbose_name='Şube KDV1')),
                ('kdv2', models.CharField(blank=True, choices=[('Aylık', 'Aylık'), ('Üç Aylık', 'Üç Aylık')], default='Aylık', max_length=100, null=True, verbose_name='Şube KDV2')),
                ('turizm', models.CharField(blank=True, choices=[('Aylık', 'Aylık'), ('Üç Aylık', 'Üç Aylık')], default='Aylık', max_length=100, null=True, verbose_name='Şube Turizm')),
                ('muhsgk', models.CharField(blank=True, choices=[('Aylık', 'Aylık'), ('Üç Aylık', 'Üç Aylık')], default='Aylık', max_length=100, null=True, verbose_name='Şube MuhSGK')),
                ('poset', models.CharField(blank=True, choices=[('Aylık', 'Aylık'), ('Üç Aylık', 'Üç Aylık'), ('Altı Aylık', 'Altı Aylık')], default='Aylık', max_length=100, null=True, verbose_name='Şube Poşet')),
                ('firma_defter_turu', models.CharField(blank=True, choices=[('İşletme', 'İşletme'), ('Serbest Meslek Defteri', 'Serbest Meslek Defteri')], default='İşletme', max_length=100, null=True, verbose_name='Firma Defter Türü ')),
                ('mukellefiyet_turu', models.CharField(blank=True, choices=[('Gerçek Kişi', 'Gerçek Kişi'), ('Adi Ortaklık', 'Adi Ortaklık'), ('Kollektif Şirket', 'Kollektif Şirket'), ('Adi Komandit Şirket', 'Adi Komandit Şirket'), ('Eshamlı Komandit Şirket', 'Eshamlı Komandit Şirket'), ('Limited Şirket', 'Limited Şirket'), ('Anonim Şirket', 'Anonim Şirket'), ('Kooperatif', 'Kooperatif'), ('Yabancı Kişi', 'Yabancı Kişi'), ('Diğer', 'Diğer'), ('Apartman Yönetimi', 'Apartman Yönetimi'), ('Avukatlık Ortaklığı', 'Avukatlık Ortaklığı'), ('Basın', 'Basın'), ('Birlik Ve Üst Birlik', 'Birlik Ve Üst Birlik'), ('Dernek', 'Dernek'), ('İş Ortaklığı', 'İş Ortaklığı'), ('Sendika', 'Sendika'), ('Site Yönetimi', 'Site Yönetimi'), ('Siyasi Parti', 'Siyasi Parti'), ('Spor Klübü', 'Spor Klübü'), ('Vakıf', 'Vakıf'), ('Kamu İktisadi Teşebbüsü', 'Kamu İktisadi Teşebbüsü'), ('Belediye İktisadi Teşebbüsü', 'Belediye İktisadi Teşebbüsü')], default='Gerçek Kişi', max_length=100, null=True, verbose_name='Mükellefiyet Türü ')),
                ('stok_bilgisi', models.CharField(blank=True, choices=[('FİFO', 'FİFO'), ('LİFO', 'LİFO'), ('Agirlikli Ortalama', 'Ağırlıklı Ortalama'), ('Basit Ortalama', 'Basit Ortalama'), ('Hareketli Agirlikli Ortalama', 'Hareketli Ağırlıklı Ortalama'), ('Her Kartın Kendi Yöntemine Göre', 'Her Kartın Kendi Yöntemine Göre')], default='FİFO', max_length=100, null=True, verbose_name='Stok Envanter Bilgileri')),
                ('gecici_vergi_orani', models.BigIntegerField(blank=True, null=True, verbose_name='Geçici Vergi Oranı %')),
                ('adres_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adresler')),
                ('bagli_oldugu_firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.firma')),
                ('vergi_dairesi_adi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vergi_dairesi')),
            ],
        ),
    ]
