# Generated by Django 4.1.2 on 2023-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_abonelik_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='firma_ozel_anahtar',
            field=models.CharField(default=1, max_length=200, verbose_name='Firma Özel Anahtar'),
            preserve_default=False,
        ),
    ]
