# Generated by Django 4.1.2 on 2023-07-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_abonelik_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hesap_kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Hesap Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
