# Generated by Django 4.1.2 on 2023-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_firma_firma_ozel_anahtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='firma_ozel_anahtar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firma Özel Anahtar'),
        ),
    ]
