# Generated by Django 4.1.2 on 2023-07-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_hesap_kayit_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hesap_kayit_tarihi',
        ),
    ]
