# Generated by Django 4.1.2 on 2023-09-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_firma_firma_ozel_anahtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresler',
            name='il',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İl'),
        ),
    ]
