# Generated by Django 4.1.2 on 2023-09-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_adresler_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='vergi_daireleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=100, verbose_name='İL')),
                ('vergi_dairesi_adi', models.CharField(max_length=200, verbose_name='Vergi Dairesi Adı')),
                ('kodu', models.BigIntegerField(verbose_name='Vergi Dairesi Kodu')),
            ],
        ),
    ]
