# Generated by Django 4.1.2 on 2023-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_vergi_daireleri_vergi_dairesi_il'),
    ]

    operations = [
        migrations.CreateModel(
            name='faliyet_bilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faliyet_kodu', models.BigIntegerField(verbose_name='Faliyet Kodu')),
                ('faliyet_adi', models.CharField(max_length=200, verbose_name='Faliyet Adı')),
                ('tehlike', models.CharField(choices=[('Tehlikeli', 'Tehlikeli'), ('Çok Tehlikeli', 'Çok Tehlikeli'), ('Az Tehlikeli', 'Az Tehlikeli')], default='Tehlikeli', max_length=100, verbose_name='Tehlike Sınıfı')),
            ],
        ),
    ]
