# Generated by Django 4.1.2 on 2023-09-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_faliyet_bilgisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='calisma_sosyal_guvenlik_is_kollari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_baslik', models.CharField(max_length=200, verbose_name='Çalışma ve Sosyal Güvenlik iş Kolu ve Kodu')),
            ],
        ),
        migrations.AlterField(
            model_name='faliyet_bilgisi',
            name='tehlike',
            field=models.CharField(choices=[('', ''), ('Tehlikeli', 'Tehlikeli'), ('Çok Tehlikeli', 'Çok Tehlikeli'), ('Az Tehlikeli', 'Az Tehlikeli')], default='', max_length=100, verbose_name='Tehlike Sınıfı'),
        ),
        migrations.CreateModel(
            name='sube_faliyet_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurulus_tarihi', models.DateField(verbose_name='Kuruluş Tarihi')),
                ('terk_tarihi', models.DateField(verbose_name='Terk Tarihi')),
                ('faliyet_niteligi', models.CharField(choices=[('', ''), ('Devamlı', 'Devamlı'), ('Mevsimlik', 'Mevsimlik'), ('Geçici', 'Geçici'), ('Diğer', 'Diğer')], default='', max_length=100, verbose_name='Faliyet Niteliği')),
                ('tabi_oldugu_sektor', models.CharField(choices=[('', ''), ('Şirket Türü', 'Şirket Türü'), ('Dernek', 'Dernek'), ('Vakıf', 'Vakıf'), ('Sendika', 'Sendika'), ('Apartman Yönetimi', 'Apartman Yönetimi'), ('Siyasi Parti', 'Siyasi Parti'), ('Spor Klüpleri', 'Spor Klüpleri'), ('Basın', 'Basın'), ('Diğer', 'Diğer')], default='', max_length=200, verbose_name='Tabi Olduğu Sektör')),
                ('yapilan_is_niteligi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yapılan İş Niteliği')),
                ('sahis_ise_ticaret_unvani', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şahıs İse Ticaret Ünvanı')),
                ('ticaret_sicil_gazete', models.DateField(verbose_name='Ticaret Sicil Gazetesi Tarihi')),
                ('ticaret_sicil_gazete_sayfa_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticaret Sicil Gazete Sayfa No')),
                ('ticaret_sicil_gazete_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticaret Sicil Gazete No')),
                ('meslek_tesekkul_adi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meslek Teşekkül Adı')),
                ('meslek_tesekkul_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meslek Teşekkül No')),
                ('adres_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres No')),
                ('taahut_edilen_sermaye', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taahüt Edilen Sermaye')),
                ('odenen_sermaye', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ödenen Sermaye')),
                ('e_posta_adresi2', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Adresi 2')),
                ('kayitli_oldugu_il', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kayıtlı Olduğu İl')),
                ('ticaret_sicil_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticaret Sicil No')),
                ('mersis_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mersis No')),
                ('isyeri_turu', models.CharField(choices=[('', ''), ('Merkez', 'Merkez'), ('Mükellefyetsiz Şube', 'Mükellefyetsiz Şube')], default='', max_length=200, verbose_name='İşyeri Türü')),
                ('isyeri_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='İşyeri Kodu')),
                ('isyeri_mulkiyet', models.CharField(choices=[('', ''), ('Kira', 'Kira'), ('Mal Sahibi', 'Mal Sahibi'), ('Diğer', 'Diğer')], default='', max_length=200, verbose_name='İşyeri Mülkiyet')),
                ('yetkili_adi_soyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yetkili Adı Soyadı')),
                ('yetkili_tckimlikno', models.CharField(blank=True, max_length=11, null=True, verbose_name='Yetkili T.C. Kimlik No')),
                ('vergi_kimlikno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Kimlik No')),
                ('oda_sicil_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bağlı Olduğu Oda Sicil No')),
                ('cevre_temizlik_vergi_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Çevre Temizlik Vergi No')),
                ('beldye_ilan_reklam_vergi_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beledye İlan Reklam Vergi No')),
                ('calisma_ve_sosyal_is_kolu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.calisma_sosyal_guvenlik_is_kollari', verbose_name='Çalişma Ve Sosya Güvenlik İş Kolu')),
                ('faliyet_nace_kodu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faliyet_bilgisi')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
                ('vergi_dairesi_adi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vergi_dairesi', verbose_name='KDV1 KDV2 Beyanname Vergi Dairesi')),
            ],
        ),
    ]
