# Generated by Django 4.1.2 on 2023-09-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_calisma_sosyal_guvenlik_is_kollari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='taseronbilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vergi_numarasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Numarası')),
                ('sahis_tc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Şahis Tc Kimlik Numarası')),
                ('email_adresi', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Şube Email Adresi ')),
                ('web_adresi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Web Adresi ')),
                ('telefon_numarasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şube Telefon Numarası ')),
                ('adres_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adresler')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
        migrations.CreateModel(
            name='ihale_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihalekonusundaihaleyapanmakam', models.CharField(blank=True, max_length=200, null=True, verbose_name='İhale Konusunda İhaleyi Yapan Makam')),
                ('isyeri_bildirgersi_imzalayan', models.CharField(choices=[('', ''), ('İşveren', 'İşveren'), ('İşveren Vekili', 'İşveren Vekili')], default='', max_length=100, verbose_name='İşyeri Bildirgesi İmzalayan')),
                ('ihalekonusundaihaleyapanmakamadresi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İhale Konusunda İhaleyi Yapan Makam Adresi')),
                ('isveren_tipi', models.CharField(choices=[('', ''), ('İşveren', 'İşveren'), ('İşveren Vekili', 'İşveren Vekili')], default='', max_length=100, verbose_name='İşveren Tipi')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
    ]
