# Generated by Django 4.1.2 on 2023-09-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_taseronbilgileri_ihale_bilgileri'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurumlar_dar_mukkelef_kimlik_ve_adres_bilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurumlarvergiveyatckimlikno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurumlar Vergi , Tc Kimlikl NO')),
                ('kurumlarvergikimlikno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurumlar Vergi Nosu')),
                ('kurumlarsoyadiunvan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Soyadı Unvan')),
                ('kurumlaradiunvan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar ADı Unvan')),
                ('kurumlarticaretsicilno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Ticaret Sicil No')),
                ('Kurumlarepostaadresi', models.EmailField(blank=True, max_length=200, null=True, verbose_name='eposta Adresi')),
                ('kurumlarirtibatnumarasi', models.CharField(blank=True, max_length=11, null=True, verbose_name='Kurumlar İrtibart Numarası')),
                ('kurumlarsube', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Bağlı Şube')),
                ('cikisyeri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Çıkış Yeri')),
                ('kurumlarajanlik', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Ajanlık')),
                ('kurmlarimalatyeri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar İmalat Yeri')),
                ('kurumlarsatisyeri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Satış Yeri')),
                ('kurumlarsair', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Sair')),
                ('kurumlartoplam', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kurumlar Toplam')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
    ]
