# Generated by Django 4.1.2 on 2023-09-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_taseronbilgileri_web_adresi'),
    ]

    operations = [
        migrations.CreateModel(
            name='beyanname_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beyannamehangisifatlaverildi', models.CharField(blank=True, choices=[('', ''), ('mukellef', 'Mükellef'), ('mirascı', 'Miradscı'), ('kanunitemsilci', 'Kanuni Temsilci')], default='', max_length=100, null=True, verbose_name='Beyanname Hangi Sıfatla Verildiği')),
                ('mirascibilgisitc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mirasci Tc Kimlik No')),
                ('mirascivergino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mirascı Vergi No')),
                ('beyannamesoyadiunvan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyadı Unvan')),
                ('beyannameadiunvandevami', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı Unvan (devamı)')),
                ('beyannameyeaitticaretsicilno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticaret Sicil No')),
                ('beyannameemailadresi', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Adresi')),
                ('beyannametelefonumarasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Numarası')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
        migrations.CreateModel(
            name='ymmbilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymmaitbilgilertc', models.CharField(blank=True, max_length=12, null=True, verbose_name='YMM AİT TC')),
                ('ymmaitbilgilervergino', models.CharField(blank=True, max_length=100, null=True, verbose_name='YMM AİT Vergi No')),
                ('ymmaitbilgilersoyadiunvan', models.CharField(blank=True, max_length=200, null=True, verbose_name='YMM AİT Soyadi Unvan')),
                ('ymmaitbilgileradiunvanbilgisi', models.CharField(blank=True, max_length=200, null=True, verbose_name='YMM AİT Adı Unvan')),
                ('ymmaitbilgileraditicaretsicilno', models.CharField(blank=True, max_length=200, null=True, verbose_name='YMM AİT Ticaret Sicil No')),
                ('ymmaitbilgilereposta', models.EmailField(blank=True, max_length=200, null=True, verbose_name='YMM AİT EPOSTA')),
                ('ymmaitbilgilertelefonbilgisi', models.CharField(blank=True, max_length=12, null=True, verbose_name='YMM AİT ;Telefon No')),
                ('beyanname_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.beyanname_bilgileri')),
            ],
        ),
        migrations.CreateModel(
            name='Beyannameyi_gonderen_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beyannamegonderentc', models.CharField(blank=True, max_length=12, null=True, verbose_name='Beyannameyi Gönderen TC')),
                ('beyannamegonderenvergino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beyanname Gönderen Vergi No')),
                ('beyannamegonderensoyadiunvan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Gönderen Soyadi Unvan')),
                ('beyannamegonderenadiunvandevami', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adı Unvan')),
                ('beyannamegonderentivaretsicilno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ticaret Sicil No')),
                ('beyannamegondereneposta', models.EmailField(blank=True, max_length=200, null=True, verbose_name='EPOSTA')),
                ('beyannamegonderentelefon', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon No')),
                ('beyanname_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.beyanname_bilgileri')),
            ],
        ),
        migrations.CreateModel(
            name='beyanname_kanuni_temsilcisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beyannamekanunitemsicitc', models.CharField(blank=True, max_length=15, null=True, verbose_name='Kanuni Temsilci Tc')),
                ('beyannamekanunitemsicivergino', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kanuni Temsilci Vergi No')),
                ('beyannamekanunitemsicisoyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kanuni Temsilci soyadı')),
                ('beyannamekanunitemsiciadiunvandevami', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kanuni Temsilci Adı Unvan Devamı')),
                ('beyannamekanunitemsiciticaretsicilno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Kanuni Temsici Ticaret Sicil No')),
                ('beyannamekanunitemsicieposta', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Beyanname Kanuni Temsicieposta')),
                ('beyannamekanunitemsicitelefon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Kanuni Temsici Telefon')),
                ('beyanname_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.beyanname_bilgileri')),
            ],
        ),
        migrations.CreateModel(
            name='beyanname_duzenleyene_ait_bilgiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beyannameduzenleyeneaittc', models.CharField(blank=True, max_length=12, null=True, verbose_name='Beyanname Düzenleyene Ait TC')),
                ('beyannameduzenleyeneaitvergino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Düzenleyene Ait Vergi NO')),
                ('beyannameduzenleyeneaitsoyadiunvan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Düzenleyene Ait Soyadı Unvan')),
                ('beyannameduzenleyeneaitadiunvandevami', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Düzenleyene Ait Adı Unvan Devamı')),
                ('beyannameduzenleyeneaitticaretsicilno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Düzenleyene Ait Ticagtet Sİcil No')),
                ('beyannameduzenleyeneaiteposta', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Beyanname Düzenleyene Ait Email')),
                ('beyannameduzenleyeneaittelefon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beyanname Düzenleyene Ait Telefon Nuımarası')),
                ('beyanname_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.beyanname_bilgileri')),
            ],
        ),
    ]
