# Generated by Django 4.1.2 on 2023-09-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_beyanname_bilgileri_ymmbilgileri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sgk_kanunlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=200, null=True, verbose_name='KAnun ADı Ve Numarası')),
            ],
        ),
        migrations.AlterField(
            model_name='sube_faliyet_bilgileri',
            name='kurulus_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Kuruluş Tarihi'),
        ),
        migrations.AlterField(
            model_name='sube_faliyet_bilgileri',
            name='terk_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Terk Tarihi'),
        ),
        migrations.AlterField(
            model_name='sube_faliyet_bilgileri',
            name='ticaret_sicil_gazete',
            field=models.DateField(blank=True, null=True, verbose_name='Ticaret Sicil Gazetesi Tarihi'),
        ),
        migrations.CreateModel(
            name='sgk_bilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgkdosyaacilistarihi', models.DateField(blank=True, null=True, verbose_name='SGK DOSYA Açılış Tarihi')),
                ('sgkdosyakapanistarihi', models.DateField(blank=True, null=True, verbose_name='SGK DOSYA Kapanış Tarihi')),
                ('sgkdosyam', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya M')),
                ('sgkdosyaiskolukod', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK İŞ KOLU KOD')),
                ('sgkdosyayeni', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Yeni')),
                ('sgkdosyaeski', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Eski')),
                ('sgkdosyaisyerisirano', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya İŞ Yeri Sıra No')),
                ('sgkdosyailkodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya İl kodu')),
                ('sgkdosyailcekodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya İl kodu')),
                ('sgkdosyakontrolno', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Kontrol No')),
                ('sgkdosyaarackodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Araç Kodu')),
                ('sgkdosyaiskodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya İş Kodu')),
                ('sgkdosyasfkbolgemud', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Bölge Müd.')),
                ('sgkdosyail', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya İL ')),
                ('sgkdosyailce', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya İlçe ')),
                ('sgkdosyatehlikederecesi', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Tehlike Derecesi ')),
                ('sgkdosyatehlikesinifi', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Tehlike Sınıfı ')),
                ('sgkdosyaprimorani', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Prim Oranı ')),
                ('sgkfazlamesaiyuzdesialt', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Alt Yüzdesi ')),
                ('sgkfazlamesaiyuzdesiust', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Üst Yüzdesi')),
                ('sgkdosyalaribesuygulamasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Bes Uygulamaları')),
                ('sgkdosyatesfik6111kanun', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya 6111 Sayılı Kanun Teşfiği')),
                ('sgkdosyatesfik6111faydalanmaayi', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya 6111 Sayılı Kanun Faydalanma Süresi')),
                ('personel_6116645yararlanmiyorsayenikanun', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya 6111 Sayılı Kanun Faydalanma Süresi')),
                ('personel_girisinde_otomatik_kanun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.sgk_kanunlari')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
    ]
