# Generated by Django 4.1.2 on 2023-09-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_sgk_kanunlari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sgk_bolgecalisma_mudurlukleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgkbolges', models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Bölge S')),
                ('sgkbolgemeslek', models.CharField(blank=True, max_length=200, null=True, verbose_name='SGK Bölge Meslek')),
                ('sgkbolgedosyano', models.CharField(blank=True, max_length=200, null=True, verbose_name='SGK Bölge Dosya No')),
                ('sgkbolgeilkodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='SGK Bölge İl Kodu')),
                ('sgkbolgeyazismaadresi', models.CharField(blank=True, max_length=200, null=True, verbose_name='SGK Bölge Adresi')),
                ('sgkbolgetaseronadisoyadi', models.CharField(blank=True, max_length=200, null=True, verbose_name='SGK Bölge Taşeron Adı Soyadı')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
        migrations.CreateModel(
            name='iskurbilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iskurisyerinumarasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İŞKUR İş Yeri Numarası')),
                ('iskurisverentc', models.CharField(blank=True, max_length=200, null=True, verbose_name='İŞKUR İşveren Tc Kimlik')),
                ('iskurilmudkayittarihi', models.DateField(blank=True, null=True, verbose_name='İŞKUR MÜD. Kayıt Tarihi')),
                ('iskursifresi', models.CharField(blank=True, max_length=200, null=True, verbose_name='İŞKUR Şifresi')),
                ('sube_bilgisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sube')),
            ],
        ),
    ]
