# Generated by Django 4.1.2 on 2023-12-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_sube_gecici_vergi_orani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beyanname_bilgileri',
            name='beyannamehangisifatlaverildi',
            field=models.CharField(blank=True, choices=[('', ''), ('mukellef', 'Mükellef'), ('mirascı', 'Mirascı'), ('kanunitemsilci', 'Kanuni Temsilci')], default='', max_length=100, null=True, verbose_name='Beyanname Hangi Sıfatla Verildiği'),
        ),
        migrations.AlterField(
            model_name='sgk_bilgileri',
            name='sgkdosyaprimorani',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya Prim Oranı '),
        ),
    ]
