# Generated by Django 4.1.2 on 2023-12-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_beyanname_bilgileri_beyannamehangisifatlaverildi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgk_bilgileri',
            name='sgkdosyaprimorani',
            field=models.FloatField(blank=True, null=True, verbose_name='SGK Dosya Prim Oranı '),
        ),
        migrations.AlterField(
            model_name='sgk_bilgileri',
            name='sgkfazlamesaiyuzdesialt',
            field=models.FloatField(blank=True, null=True, verbose_name='SGK Dosya Alt Yüzdesi '),
        ),
        migrations.AlterField(
            model_name='sgk_bilgileri',
            name='sgkfazlamesaiyuzdesiust',
            field=models.FloatField(blank=True, null=True, verbose_name='SGK Dosya Üst Yüzdesi'),
        ),
    ]
