# Generated by Django 4.1.2 on 2023-12-31 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_sgk_bilgileri_sgkdosyaprimorani_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgk_bilgileri',
            name='personel_6116645yararlanmiyorsayenikanun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ikinci_kanun', to='users.sgk_kanunlari'),
        ),
    ]
