# Generated by Django 4.1.2 on 2023-12-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_sgk_bilgileri_personel_6116645yararlanmiyorsayenikanun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgk_bilgileri',
            name='personel_6116645yararlanmiyorsayenikanun',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SGK Dosya 6111 Sayılı Kanun Faydalanma Süresi'),
        ),
    ]
